pyml_bindgen is not compatible with base v0.17
```
=== ERROR while compiling pyml_bindgen.0.3.0 =================================#
 context              2.2.0~rc1~dev | linux/x86_64 | ocaml-base-compiler.5.2.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.2/.opam-switch/build/pyml_bindgen.0.3.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p pyml_bindgen -j 255 @install
 exit-code            1
 env-file             ~/.opam/log/pyml_bindgen-8-01f992.env
 output-file          ~/.opam/log/pyml_bindgen-8-01f992.out
 (cd _build/default && /home/opam/.opam/5.2/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I lib/.lib.objs/byte -I /home/opam/.opam/5.2/lib/angstrom -I /home/opam/.opam/5.2/lib/base -I /home/opam/.opam/5.2/lib/base/base_internalhash_types -I /home/opam/.opam/5.2/lib/base/md5 -I /home/opam/.opam/5.2/lib/base/shadow_stdlib -I /home/opam/.opam/5.2/lib/base_bigstring -I /home/opam/.opam/5.2/lib/base_quickcheck -I /home/opam/.opam/5.2/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/5.2/lib/bigstringaf -I /home/opam/.opam/5.2/lib/bin_prot -I /home/opam/.opam/5.2/lib/bin_prot/shape -I /home/opam/.opam/5.2/lib/core -I /home/opam/.opam/5.2/lib/core/base_for_tests -I /home/opam/.opam/5.2/lib/core/command -I /home/opam/.opam/5.2/lib/core/filename_base -I /home/opam/.opam/5.2/lib/core/heap_block -I /home/opam/.opam/5.2/lib/core/univ_map -I /home/opam/.opam/5.2/lib/core/validate -I /home/opam/.opam/5.2/lib/fieldslib -I /home/opam/.opam/5.2/lib/gel -I /home/opam/.opam/5.2/lib/int_repr -I /home/opam/.opam/5.2/lib/jane-street-headers -I /home/opam/.opam/5.2/lib/jane_rope -I /home/opam/.opam/5.2/lib/ocaml_intrinsics_kernel -I /home/opam/.opam/5.2/lib/parsexp -I /home/opam/.opam/5.2/lib/ppx_assert/runtime-lib -I /home/opam/.opam/5.2/lib/ppx_bench/runtime-lib -I /home/opam/.opam/5.2/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.2/lib/ppx_diff/diffable -I /home/opam/.opam/5.2/lib/ppx_diff/diffable_cinaps -I /home/opam/.opam/5.2/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.2/lib/ppx_expect/config -I /home/opam/.opam/5.2/lib/ppx_expect/config_types -I /home/opam/.opam/5.2/lib/ppx_expect/make_corrected_file -I /home/opam/.opam/5.2/lib/ppx_expect/runtime -I /home/opam/.opam/5.2/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.2/lib/ppx_here/runtime-lib -I /home/opam/.opam/5.2/lib/ppx_inline_test/config -I /home/opam/.opam/5.2/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.2/lib/ppx_log/syntax -I /home/opam/.opam/5.2/lib/ppx_log/types -I /home/opam/.opam/5.2/lib/ppx_module_timer/runtime -I /home/opam/.opam/5.2/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.2/lib/ppx_stable_witness/runtime -I /home/opam/.opam/5.2/lib/ppx_stable_witness/stable_witness -I /home/opam/.opam/5.2/lib/ppx_string/runtime -I /home/opam/.opam/5.2/lib/ppxlib/print_diff -I /home/opam/.opam/5.2/lib/re2 -I /home/opam/.opam/5.2/lib/re2/c -I /home/opam/.opam/5.2/lib/regex_parser_intf -I /home/opam/.opam/5.2/lib/sexplib -I /home/opam/.opam/5.2/lib/sexplib0 -I /home/opam/.opam/5.2/lib/splittable_random -I /home/opam/.opam/5.2/lib/stdio -I /home/opam/.opam/5.2/lib/time_now -I /home/opam/.opam/5.2/lib/typerep -I /home/opam/.opam/5.2/lib/variantslib -no-alias-deps -open Lib -o lib/.lib.objs/byte/lib__Utils.cmo -c -impl lib/utils.pp.ml)
 File "lib/utils.ml", line 71, characters 2-11:
 71 |   Caml.exit exit_code
        ^^^^^^^^^
 Alert deprecated: module Base.Caml
 [since 2023-01] use Stdlib instead of Caml

 File "lib/utils.ml", line 71, characters 2-11:
 71 |   Caml.exit exit_code
        ^^^^^^^^^
 Error: Unbound value "Caml.exit"
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>