caqti 1.0.0-1.1.0 are not compatible with ocaml 5
```
=== ERROR while compiling caqti.1.1.0 ========================================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.0/.opam-switch/build/caqti.1.1.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p caqti -j 31
 exit-code            1
 env-file             ~/.opam/log/caqti-8-e86afd.env
 output-file          ~/.opam/log/caqti-8-e86afd.out
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.caqti.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/uri -intf-suffix .ml -no-alias-deps -o lib/.caqti.objs/byte/caqti_type.cmo -c -impl lib/caqti_type.ml)
 File "lib/caqti_type.ml", line 47, characters 13-38:
 47 |     let ec = Obj.extension_constructor ft in
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
 Error: Unbound value Obj.extension_constructor
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I lib/.caqti.objs/byte -I lib/.caqti.objs/native -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/uri -intf-suffix .ml -no-alias-deps -o lib/.caqti.objs/native/caqti_type.cmx -c -impl lib/caqti_type.ml)
 File "lib/caqti_type.ml", line 47, characters 13-38:
 47 |     let ec = Obj.extension_constructor ft in
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
 Error: Unbound value Obj.extension_constructor
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.caqti.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/uri -intf-suffix .ml -no-alias-deps -o lib/.caqti.objs/byte/caqti_error.cmo -c -impl lib/caqti_error.ml)
 File "lib/caqti_error.ml", line 26, characters 10-35:
 26 |   let c = Obj.extension_constructor msg in
                ^^^^^^^^^^^^^^^^^^^^^^^^^
 Error: Unbound value Obj.extension_constructor
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.caqti.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/uri -no-alias-deps -opaque -o lib/.caqti.objs/byte/caqti_driver_sig.cmi -c -intf lib/caqti_driver_sig.mli)
 File "_none_", line 1:
 Alert ocaml_deprecated_auto_include:
 OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
 automatically added to the search path, but you should add -I +unix to the
 command-line to silence this alert (e.g. by adding unix to the list of
 libraries in your dune file, or adding use_unix to your _tags file for
 ocamlbuild, or using -package unix for ocamlfind).
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.caqti.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/uri -intf-suffix .ml -no-alias-deps -o lib/.caqti.objs/byte/caqti_pool.cmo -c -impl lib/caqti_pool.ml)
 File "lib/caqti_pool.ml", line 28, characters 56-74:
 28 |     let compare {priority = pA; _} {priority = pB; _} = Pervasives.compare pB pA
                                                              ^^^^^^^^^^^^^^^^^^
 Error: Unbound module Pervasives
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>