restrict yaml.0.2.1 to ocaml 4.06.0 or higher
due to
```
Error: variable "ocamlopt_cflags" not found in the output of `/home/opam/.opam/4.05.0/bin/ocamlc.opt -config`
```