gsl 1.24.3 is not compatible with ocaml 5
Fails with many c API errors, for example
```
 (cd _build/default/src && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -fPIC -DPIC -Wno-unused-parameter -g -I /home/opam/.opam/5.0/lib/ocaml -o mlgsl_cdf.o -c mlgsl_cdf.c)
 In file included from mlgsl_cdf.c:2:
 wrappers.h: In function 'copy_two_double':
 wrappers.h:34:8: warning: implicit declaration of function 'copy_double'; did you mean 'copy_two_double'? [-Wimplicit-function-declaration]
    34 |   va = copy_double(a);
       |        ^~~~~~~~~~~
       |        copy_two_double
 wrappers.h:36:7: warning: implicit declaration of function 'alloc_small'; did you mean 'caml_alloc_small'? [-Wimplicit-function-declaration]
    36 |   r = alloc_small(2, 0);
       |       ^~~~~~~~~~~
       |       caml_alloc_small
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>