paf-cohttp not compatible with new cohttp
Fails with
```
File "lib/paf_cohttp.ml", line 1:
Error: The implementation lib/paf_cohttp.ml
       does not match the interface lib/.paf_cohttp.objs/byte/paf_cohttp.cmi:
        The value `set_cache' is required but not provided
       File "cohttp-lwt/src/s.ml", line 190, characters 2-30:
         Expected declaration
(cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.paf_cohttp.objs/byte -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigarray-compat -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cohttp -I /home/opam/.opam/4.14/lib/cohttp-lwt -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/http -I /home/opam/.opam/4.14/lib/httpaf -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/paf -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/re -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/rresult -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uri-sexp -intf-suffix .ml -no-alias-deps -o lib/.paf_cohttp.objs/byte/paf_cohttp.cmo -c -impl lib/paf_cohttp.ml)
File "lib/paf_cohttp.ml", line 1:
Error: The implementation lib/paf_cohttp.ml
       does not match the interface lib/.paf_cohttp.objs/byte/paf_cohttp.cmi:
        The value `set_cache' is required but not provided
       File "cohttp-lwt/src/s.ml", line 190, characters 2-30:
         Expected declaration
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>