websocket-async is not compatible with cohttp6
```
=== ERROR while compiling websocket-async.2.16 ===============================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.0/.opam-switch/build/websocket-async.2.16
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p websocket-async -j 255 --promote-install-files=false @install
 exit-code            1
 env-file             ~/.opam/log/websocket-async-7-83c96e.env
 output-file          ~/.opam/log/websocket-async-7-83c96e.out
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I async/.websocket_async.objs/byte -I async/.websocket_async.objs/native -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/astring -I /home/opam/.opam/5.0/lib/async -I /home/opam/.opam/5.0/lib/async/async_command -I /home/opam/.opam/5.0/lib/async/async_quickcheck -I /home/opam/.opam/5.0/lib/async/async_rpc -I /home/opam/.opam/5.0/lib/async_kernel -I /home/opam/.opam/5.0/lib/async_kernel/config -I /home/opam/.opam/5.0/lib/async_kernel/persistent_connection_kernel -I /home/opam/.opam/5.0/lib/async_kernel/read_write_pair -I /home/opam/.opam/5.0/lib/async_rpc_kernel -I /home/opam/.opam/5.0/lib/async_unix -I /home/opam/.opam/5.0/lib/async_unix/thread_pool -I /home/opam/.opam/5.0/lib/async_unix/thread_safe_ivar -I /home/opam/.opam/5.0/lib/base -I /home/opam/.opam/5.0/lib/base/base_internalhash_types -I /home/opam/.opam/5.0/lib/base/caml -I /home/opam/.opam/5.0/lib/base/md5 -I /home/opam/.opam/5.0/lib/base/shadow_stdlib -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/base_bigstring -I /home/opam/.opam/5.0/lib/base_quickcheck -I /home/opam/.opam/5.0/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bin_prot -I /home/opam/.opam/5.0/lib/bin_prot/shape -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/cohttp -I /home/opam/.opam/5.0/lib/cohttp-async -I /home/opam/.opam/5.0/lib/conduit -I /home/opam/.opam/5.0/lib/conduit-async -I /home/opam/.opam/5.0/lib/core -I /home/opam/.opam/5.0/lib/core/base_for_tests -I /home/opam/.opam/5.0/lib/core/validate -I /home/opam/.opam/5.0/lib/core_kernel/bounded_int_table -I /home/opam/.opam/5.0/lib/core_kernel/caml_threads -I /home/opam/.opam/5.0/lib/core_kernel/caml_unix -I /home/opam/.opam/5.0/lib/core_kernel/flags -I /home/opam/.opam/5.0/lib/core_kernel/iobuf -I /home/opam/.opam/5.0/lib/core_kernel/moption -I /home/opam/.opam/5.0/lib/core_kernel/pairing_heap -I /home/opam/.opam/5.0/lib/core_kernel/sexp_hidden_in_test -I /home/opam/.opam/5.0/lib/core_kernel/thread_pool_cpu_affinity -I /home/opam/.opam/5.0/lib/core_kernel/thread_safe_queue -I /home/opam/.opam/5.0/lib/core_kernel/timing_wheel -I /home/opam/.opam/5.0/lib/core_kernel/tuple_pool -I /home/opam/.opam/5.0/lib/core_kernel/uopt -I /home/opam/.opam/5.0/lib/core_kernel/uuid -I /home/opam/.opam/5.0/lib/core_unix -I /home/opam/.opam/5.0/lib/core_unix/bigstring_unix -I /home/opam/.opam/5.0/lib/core_unix/core_thread -I /home/opam/.opam/5.0/lib/core_unix/error_checking_mutex -I /home/opam/.opam/5.0/lib/core_unix/filename_unix -I /home/opam/.opam/5.0/lib/core_unix/iobuf_unix -I /home/opam/.opam/5.0/lib/core_unix/linux_ext -I /home/opam/.opam/5.0/lib/core_unix/nano_mutex -I /home/opam/.opam/5.0/lib/core_unix/ocaml_c_utils -I /home/opam/.opam/5.0/lib/core_unix/signal_unix -I /home/opam/.opam/5.0/lib/core_unix/squeue -I /home/opam/.opam/5.0/lib/core_unix/sys_unix -I /home/opam/.opam/5.0/lib/core_unix/time_ns_unix -I /home/opam/.opam/5.0/lib/core_unix/time_stamp_counter -I /home/opam/.opam/5.0/lib/core_unix/time_unix -I /home/opam/.opam/5.0/lib/core_unix/uuid -I /home/opam/.opam/5.0/lib/domain-name -I /home/opam/.opam/5.0/lib/fieldslib -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/http -I /home/opam/.opam/5.0/lib/http/__private__/http_bytebuffer -I /home/opam/.opam/5.0/lib/int_repr -I /home/opam/.opam/5.0/lib/ipaddr -I /home/opam/.opam/5.0/lib/ipaddr-sexp -I /home/opam/.opam/5.0/lib/ipaddr/unix -I /home/opam/.opam/5.0/lib/jane-street-headers -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/logs-async -I /home/opam/.opam/5.0/lib/macaddr -I /home/opam/.opam/5.0/lib/magic-mime -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocaml_intrinsics -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/ppx_assert/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_bench/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_expect/collector -I /home/opam/.opam/5.0/lib/ppx_expect/common -I /home/opam/.opam/5.0/lib/ppx_expect/config -I /home/opam/.opam/5.0/lib/ppx_expect/config_types -I /home/opam/.opam/5.0/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_here/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_inline_test/config -I /home/opam/.opam/5.0/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_log/types -I /home/opam/.opam/5.0/lib/ppx_module_timer/runtime -I /home/opam/.opam/5.0/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.0/lib/protocol_version_header -I /home/opam/.opam/5.0/lib/re -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib/unix -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/spawn -I /home/opam/.opam/5.0/lib/splittable_random -I /home/opam/.opam/5.0/lib/stdio -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/time_now -I /home/opam/.opam/5.0/lib/timezone -I /home/opam/.opam/5.0/lib/typerep -I /home/opam/.opam/5.0/lib/uri -I /home/opam/.opam/5.0/lib/uri-sexp -I /home/opam/.opam/5.0/lib/uri/services -I /home/opam/.opam/5.0/lib/variantslib -I /home/opam/.opam/5.0/lib/websocket -intf-suffix .ml -no-alias-deps -o async/.websocket_async.objs/native/websocket_async.cmx -c -impl async/websocket_async.ml)
 File "async/websocket_async.ml", line 25, characters 34-49:
 25 | module Async_IO = Websocket.Make (Cohttp_async.Io)
                                        ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_async.Io
 This module is not for public consumption
 File "async/websocket_async.ml", line 25, characters 18-50:
 25 | module Async_IO = Websocket.Make (Cohttp_async.Io)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 Error: Modules do not match:
        sig
          module IO = Cohttp_async__Io.IO
          module Request = Cohttp_async.Io.Request
          module Response = Cohttp_async.Io.Response
        end
      is not included in Cohttp.S.IO
      The type `t' is required but not provided
      File "cohttp/src/s.ml", line 23, characters 2-12: Expected declaration
      The value `>>=' is required but not provided
      File "cohttp/src/s.ml", line 26, characters 2-44: Expected declaration
      The value `return' is required but not provided
      File "cohttp/src/s.ml", line 30, characters 2-25: Expected declaration
      The type `ic' is required but not provided
      File "cohttp/src/s.ml", line 33, characters 2-9: Expected declaration
      The type `oc' is required but not provided
      File "cohttp/src/s.ml", line 36, characters 2-9: Expected declaration
      The type `conn' is required but not provided
      File "cohttp/src/s.ml", line 39, characters 2-11: Expected declaration
      The value `refill' is required but not provided
      File "cohttp/src/s.ml", line 42, characters 2-37: Expected declaration
      The value `with_input_buffer' is required but not provided
      File "cohttp/src/s.ml", lines 44-45, characters 2-60:
        Expected declaration
      The value `read_line' is required but not provided
      File "cohttp/src/s.ml", line 47, characters 2-39: Expected declaration
      The value `read' is required but not provided
      File "cohttp/src/s.ml", line 52, characters 2-34: Expected declaration
      The value `write' is required but not provided
      File "cohttp/src/s.ml", line 59, characters 2-36: Expected declaration
      The value `flush' is required but not provided
      File "cohttp/src/s.ml", line 63, characters 2-26: Expected declaration
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I async/.websocket_async.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/astring -I /home/opam/.opam/5.0/lib/async -I /home/opam/.opam/5.0/lib/async/async_command -I /home/opam/.opam/5.0/lib/async/async_quickcheck -I /home/opam/.opam/5.0/lib/async/async_rpc -I /home/opam/.opam/5.0/lib/async_kernel -I /home/opam/.opam/5.0/lib/async_kernel/config -I /home/opam/.opam/5.0/lib/async_kernel/persistent_connection_kernel -I /home/opam/.opam/5.0/lib/async_kernel/read_write_pair -I /home/opam/.opam/5.0/lib/async_rpc_kernel -I /home/opam/.opam/5.0/lib/async_unix -I /home/opam/.opam/5.0/lib/async_unix/thread_pool -I /home/opam/.opam/5.0/lib/async_unix/thread_safe_ivar -I /home/opam/.opam/5.0/lib/base -I /home/opam/.opam/5.0/lib/base/base_internalhash_types -I /home/opam/.opam/5.0/lib/base/caml -I /home/opam/.opam/5.0/lib/base/md5 -I /home/opam/.opam/5.0/lib/base/shadow_stdlib -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/base_bigstring -I /home/opam/.opam/5.0/lib/base_quickcheck -I /home/opam/.opam/5.0/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bin_prot -I /home/opam/.opam/5.0/lib/bin_prot/shape -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/cohttp -I /home/opam/.opam/5.0/lib/cohttp-async -I /home/opam/.opam/5.0/lib/conduit -I /home/opam/.opam/5.0/lib/conduit-async -I /home/opam/.opam/5.0/lib/core -I /home/opam/.opam/5.0/lib/core/base_for_tests -I /home/opam/.opam/5.0/lib/core/validate -I /home/opam/.opam/5.0/lib/core_kernel/bounded_int_table -I /home/opam/.opam/5.0/lib/core_kernel/caml_threads -I /home/opam/.opam/5.0/lib/core_kernel/caml_unix -I /home/opam/.opam/5.0/lib/core_kernel/flags -I /home/opam/.opam/5.0/lib/core_kernel/iobuf -I /home/opam/.opam/5.0/lib/core_kernel/moption -I /home/opam/.opam/5.0/lib/core_kernel/pairing_heap -I /home/opam/.opam/5.0/lib/core_kernel/sexp_hidden_in_test -I /home/opam/.opam/5.0/lib/core_kernel/thread_pool_cpu_affinity -I /home/opam/.opam/5.0/lib/core_kernel/thread_safe_queue -I /home/opam/.opam/5.0/lib/core_kernel/timing_wheel -I /home/opam/.opam/5.0/lib/core_kernel/tuple_pool -I /home/opam/.opam/5.0/lib/core_kernel/uopt -I /home/opam/.opam/5.0/lib/core_kernel/uuid -I /home/opam/.opam/5.0/lib/core_unix -I /home/opam/.opam/5.0/lib/core_unix/bigstring_unix -I /home/opam/.opam/5.0/lib/core_unix/core_thread -I /home/opam/.opam/5.0/lib/core_unix/error_checking_mutex -I /home/opam/.opam/5.0/lib/core_unix/filename_unix -I /home/opam/.opam/5.0/lib/core_unix/iobuf_unix -I /home/opam/.opam/5.0/lib/core_unix/linux_ext -I /home/opam/.opam/5.0/lib/core_unix/nano_mutex -I /home/opam/.opam/5.0/lib/core_unix/ocaml_c_utils -I /home/opam/.opam/5.0/lib/core_unix/signal_unix -I /home/opam/.opam/5.0/lib/core_unix/squeue -I /home/opam/.opam/5.0/lib/core_unix/sys_unix -I /home/opam/.opam/5.0/lib/core_unix/time_ns_unix -I /home/opam/.opam/5.0/lib/core_unix/time_stamp_counter -I /home/opam/.opam/5.0/lib/core_unix/time_unix -I /home/opam/.opam/5.0/lib/core_unix/uuid -I /home/opam/.opam/5.0/lib/domain-name -I /home/opam/.opam/5.0/lib/fieldslib -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/http -I /home/opam/.opam/5.0/lib/int_repr -I /home/opam/.opam/5.0/lib/ipaddr -I /home/opam/.opam/5.0/lib/ipaddr-sexp -I /home/opam/.opam/5.0/lib/ipaddr/unix -I /home/opam/.opam/5.0/lib/jane-street-headers -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/logs-async -I /home/opam/.opam/5.0/lib/macaddr -I /home/opam/.opam/5.0/lib/magic-mime -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ocaml_intrinsics -I /home/opam/.opam/5.0/lib/ocplib-endian -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/ppx_assert/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_bench/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_expect/collector -I /home/opam/.opam/5.0/lib/ppx_expect/common -I /home/opam/.opam/5.0/lib/ppx_expect/config -I /home/opam/.opam/5.0/lib/ppx_expect/config_types -I /home/opam/.opam/5.0/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_here/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_inline_test/config -I /home/opam/.opam/5.0/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_log/types -I /home/opam/.opam/5.0/lib/ppx_module_timer/runtime -I /home/opam/.opam/5.0/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.0/lib/protocol_version_header -I /home/opam/.opam/5.0/lib/re -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib/unix -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/spawn -I /home/opam/.opam/5.0/lib/splittable_random -I /home/opam/.opam/5.0/lib/stdio -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/time_now -I /home/opam/.opam/5.0/lib/timezone -I /home/opam/.opam/5.0/lib/typerep -I /home/opam/.opam/5.0/lib/uri -I /home/opam/.opam/5.0/lib/uri-sexp -I /home/opam/.opam/5.0/lib/uri/services -I /home/opam/.opam/5.0/lib/variantslib -I /home/opam/.opam/5.0/lib/websocket -intf-suffix .ml -no-alias-deps -o async/.websocket_async.objs/byte/websocket_async.cmo -c -impl async/websocket_async.ml)
 File "async/websocket_async.ml", line 25, characters 34-49:
 25 | module Async_IO = Websocket.Make (Cohttp_async.Io)
                                        ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_async.Io
 This module is not for public consumption
 File "async/websocket_async.ml", line 25, characters 18-50:
 25 | module Async_IO = Websocket.Make (Cohttp_async.Io)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 Error: Modules do not match:
        sig
          module IO = Cohttp_async__Io.IO
          module Request = Cohttp_async.Io.Request
          module Response = Cohttp_async.Io.Response
        end
      is not included in Cohttp.S.IO
      The type `t' is required but not provided
      File "cohttp/src/s.ml", line 23, characters 2-12: Expected declaration
      The value `>>=' is required but not provided
      File "cohttp/src/s.ml", line 26, characters 2-44: Expected declaration
      The value `return' is required but not provided
      File "cohttp/src/s.ml", line 30, characters 2-25: Expected declaration
      The type `ic' is required but not provided
      File "cohttp/src/s.ml", line 33, characters 2-9: Expected declaration
      The type `oc' is required but not provided
      File "cohttp/src/s.ml", line 36, characters 2-9: Expected declaration
      The type `conn' is required but not provided
      File "cohttp/src/s.ml", line 39, characters 2-11: Expected declaration
      The value `refill' is required but not provided
      File "cohttp/src/s.ml", line 42, characters 2-37: Expected declaration
      The value `with_input_buffer' is required but not provided
      File "cohttp/src/s.ml", lines 44-45, characters 2-60:
        Expected declaration
      The value `read_line' is required but not provided
      File "cohttp/src/s.ml", line 47, characters 2-39: Expected declaration
      The value `read' is required but not provided
      File "cohttp/src/s.ml", line 52, characters 2-34: Expected declaration
      The value `write' is required but not provided
      File "cohttp/src/s.ml", line 59, characters 2-36: Expected declaration
      The value `flush' is required but not provided
      File "cohttp/src/s.ml", line 63, characters 2-26: Expected declaration
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>