mirage-http conflicts with cohttp 0.18
Error was:

    Error: Signature mismatch:
    [...]
       The field `sexp_of_ctx' is required but not provided
       The field `close' is required but not provided
       The field `close_out' is required but not provided
       The field `close_in' is required but not provided
       The field `connect_uri' is required but not provided
       The field `default_ctx' is required but not provided
       The field `ctx' is required but not provided