cryptokit requires ocaml <4.03.0 to compile
Due to removed uint32 typedef:

```
src/stubs-md5.c:21:9: error: unknown type name 'uint32'
  uint32 buf[4];
  ^
```