Sundialsml: more x-ci-accept-failure
Compilation error:

> Some errors occurred during configuration:
 	Can't link C code to sundials.  Is sundials installed properly?
 	Saved test code as __configure_test_file__realtype.c
 	Compilation command was:
 	cc  -o __configure_test_file__realtype __configure_test_file__realtype.c

It happend on ubuntu 25.10, debian-13. Ubuntu 24.04 is fine.
It looks like right include paths are missing, for example adding this
helps: ` $(pkg-config --cflags-only-I ompi) `

Signed-off-by: Kakadu <kakadu.hafanana@gmail.com>