jekyll-format requires a recent version of ezjsonm
Otherwise it fails with:

```
 File "src/jekyll_format.ml", line 66, characters 25-48:
 66 |         Fmt.pf fmt "%s" (Ezjsonm.value_to_string v))
                               ^^^^^^^^^^^^^^^^^^^^^^^
 Error: Unbound value Ezjsonm.value_to_string
```