conduit 0.7.x conflict with tls 0.4.0+ due to:
```
  File "lib/conduit_lwt_tls.ml", line 62, characters 35-47:
  Error: The function applied to this argument has type
           ?ciphers:Tls.Ciphersuite.ciphersuite list ->
           ?version:Tls.Core.tls_version * Tls.Core.tls_version ->
           ?hashes:Nocrypto.Hash.hash list ->
           ?reneg:bool ->
           ?certificates:Tls.Config.own_cert ->
           ?authenticator:X509_lwt.authenticator -> Tls.Config.server
  This argument cannot be applied with label ~certificate
```