Do not build lambqml.0.7 on OCaml 5
FTBFS due do removal of `hash_variant` in the C API:

    + /home/opam/.opam/opam-init/hooks/sandbox.sh "build" "dune" "build" "-p" "lablqml" "-j" "71" (CWD=/home/opam/.opam/5.0/.opam-switch/build/lablqml.0.7)
    - File "lib/dune", line 22, characters 3-10:
    - 22 |    variant
    -         ^^^^^^^
    - (cd _build/default/lib && /usr/bin/gcc -DQT_QUICK_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -DQT_GUI_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -DQT_QMLMODELS_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -Wall -std=c++11 -O3 -I . -Dprivate=public -fPIC -g -I /home/opam/.opam/5.0/lib/ocaml -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -o variant.o -c variant.cpp)
    - variant.cpp: In function 'value Val_QVariant(value, const QVariant&)':
    - variant.cpp:37:17: error: 'hash_variant' was not declared in this scope
    -    37 |         _dest = hash_variant("empty");
    -       |                 ^~~~~~~~~~~~
    - In file included from /home/opam/.opam/5.0/lib/ocaml/caml/callback.h:22,
    -                  from ./lablqml.h:6,
    -                  from variant.h:1,
    -                  from variant.cpp:1:
    - variant.cpp:44:35: error: 'hash_variant' was not declared in this scope
    -    44 |             Store_field(_dest, 0, hash_variant("bool"));
    -       |                                   ^~~~~~~~~~~~