Add constraints to secp256k1-internal packages re: ocaml5
Version 0.3.0 causes linking issues under ocaml5. E.g.,

```
 === ERROR while compiling tezos-version.16.0~rc1 =============================#
  context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | pinned(https://gitlab.com/tezos/tezos/-/archive/v16.0-rc1/tezos-16.0-rc1.tar.gz)
  path                 ~/.opam/5.0/.opam-switch/build/tezos-version.16.0~rc1
  command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p tezos-version -j 127
  exit-code            1
  env-file             ~/.opam/log/tezos-version-7-de3b79.env
  output-file          ~/.opam/log/tezos-version-7-de3b79.out
    output ###
  File "src/lib_version/exe/dune", line 12, characters 7-26:
  12 |  (name tezos_print_version)
              ^^^^^^^^^^^^^^^^^^^
  (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt …
  /usr/bin/ld: /home/opam/.opam/5.0/lib/secp256k1-internal/liblibsecp256k1_stubs.a(secp256k1_wrap.o): in function `alloc_context':
  /home/opam/.opam/5.0/.opam-switch/build/secp256k1-internal.0.3.0/_build/default/src/secp256k1_wrap.c:28: undefined reference to `alloc_custom'
  /usr/bin/ld: /home/opam/.opam/5.0/.opam-switch/build/secp256k1-internal.0.3.0/_build/default/src/secp256k1_wrap.c:28: undefined reference to `alloc_custom'
  collect2: error: ld returned 1 exit status
  File "caml_startup", line 1:
  Error: Error during linking (exit code 1)
```