chamelon: add pxx_cstruct dependency
the error is:
```
=== ERROR while compiling chamelon.0.1.2 =====================================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.0/.opam-switch/build/chamelon.0.1.2
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p chamelon -j 127
 exit-code            1
 env-file             ~/.opam/log/chamelon-7-c24717.env
 output-file          ~/.opam/log/chamelon-7-c24717.out
 File "lib/dune", line 5, characters 19-30:
 5 |   (preprocess (pps ppx_cstruct))
                        ^^^^^^^^^^^
 Error: Library "ppx_cstruct" not found.
 -> required by library "chamelon" in _build/default/lib
 -> required by _build/default/META.chamelon
 -> required by _build/install/default/lib/chamelon/META
 -> required by _build/default/chamelon.install
 -> required by alias install
```

Alternatively, an upper bound (mirage-logs < 1.3.0) could have been added