Update batteries lower bound
```

#=== ERROR while compiling molenc.5.0.0 =======================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.05.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.05/.opam-switch/build/molenc.5.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p molenc -j 31
# exit-code            1
# env-file             ~/.opam/log/molenc-6-82309f.env
# output-file          ~/.opam/log/molenc-6-82309f.out
### output ###
#       ocamlc src/.encoder.eobjs/byte/uniq.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.encoder.eobjs/byte -I /home/opam/.opam/4.05/lib/batteries -I /home/opam/.opam/4.05/lib/bst -I /home/opam/.opam/4.05/lib/bytes -I /home/opam/.opam/4.05/lib/dolog -I /home/opam/.opam/4.05/lib/minicli -I /home/opam/.opam/4.05/lib/num -I /home/opam/.opam/4.05/lib/ocaml/threads -I /home/opam/.opam/4.05/lib/parmap -I src/.molenc.objs/byte -I src/.molenc.objs/native -no-alias-deps -o src/.encoder.eobjs/byte/uniq.cmo -c -impl src/uniq.ml)
# File "src/uniq.ml", line 34, characters 22-40:
# Error: Unbound value String.cut_on_char
#       ocamlc src/.encoder.eobjs/byte/butina.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.encoder.eobjs/byte -I /home/opam/.opam/4.05/lib/batteries -I /home/opam/.opam/4.05/lib/bst -I /home/opam/.opam/4.05/lib/bytes -I /home/opam/.opam/4.05/lib/dolog -I /home/opam/.opam/4.05/lib/minicli -I /home/opam/.opam/4.05/lib/num -I /home/opam/.opam/4.05/lib/ocaml/threads -I /home/opam/.opam/4.05/lib/parmap -I src/.molenc.objs/byte -I src/.molenc.objs/native -no-alias-deps -o src/.encoder.eobjs/byte/butina.cmo -c -impl src/butina.ml)
# File "src/butina.ml", line 70, characters 4-17:
# Error: This function has type ('a -> 'b) -> 'a list -> ?ncores:int -> 'b list
#        It is applied to too many arguments; maybe you forgot a `;'.
```
String.cut_on_char was added in 2.9.0