restrict git-mirage 3.13.0 3.14.0 3.15.0 to mirage-flow < 4.0.0
=== ERROR while compiling git-mirage.3.13.0 ==================================#
 context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/git-mirage.3.13.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p git-mirage -j 31
 exit-code            1
 env-file             ~/.opam/log/git-mirage-7-ed8b26.env
 output-file          ~/.opam/log/git-mirage-7-ed8b26.out
== output ###
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -g -I src/git-mirage/.git_mirage_http.objs/byte -I src/git-mirage/.git_mirage_http.objs/native -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/ca-certs-nss -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/git-paf -I /home/opam/.opam/4.14/lib/git/nss/git -I /home/opam/.opam/4.14/lib/hex -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mimic-happy-eyeballs -I /home/opam/.opam/4.14/lib/mirage-clock -I /home/opam/.opam/4.14/lib/mirage-crypto -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/mirage-time -I /home/opam/.opam/4.14/lib/ptime -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/tcpip -I /home/opam/.opam/4.14/lib/tls -I /home/opam/.opam/4.14/lib/tls-mirage -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/x509 -intf-suffix .ml -no-alias-deps -o src/git-mirage/.git_mirage_http.objs/native/git_mirage_http.cmx -c -impl src/git-mirage/git_mirage_http.ml)
 File "src/git-mirage/git_mirage_http.ml", line 198, characters 73-77:
 198 |   let http_endpoint, http_protocol = Mimic.register ~name:"http" (module HTTP)
                                                                                ^^^^
 Error: Signature mismatch:
        ...
        The value `shutdown' is required but not provided
        File "src/mirage_flow.mli", line 98, characters 2-71:
          Expected declaration
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git-mirage/.git_mirage_http.objs/byte -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/ca-certs-nss -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/git-paf -I /home/opam/.opam/4.14/lib/git/nss/git -I /home/opam/.opam/4.14/lib/hex -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mimic-happy-eyeballs -I /home/opam/.opam/4.14/lib/mirage-clock -I /home/opam/.opam/4.14/lib/mirage-crypto -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/mirage-time -I /home/opam/.opam/4.14/lib/ptime -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/tcpip -I /home/opam/.opam/4.14/lib/tls -I /home/opam/.opam/4.14/lib/tls-mirage -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/x509 -intf-suffix .ml -no-alias-deps -o src/git-mirage/.git_mirage_http.objs/byte/git_mirage_http.cmo -c -impl src/git-mirage/git_mirage_http.ml)
 File "src/git-mirage/git_mirage_http.ml", line 198, characters 73-77:
 198 |   let http_endpoint, http_protocol = Mimic.register ~name:"http" (module HTTP)
                                                                                ^^^^
 Error: Signature mismatch:
        ...
        The value `shutdown' is required but not provided
        File "src/mirage_flow.mli", line 98, characters 2-71:
          Expected declaration