dns 5.0.x is not compatible with ocaml 5, notived in #22358:
=== ERROR while compiling dns.5.0.0 ==========================================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.0.0+trunk | file:///home/opam/opam-repository
 path                 ~/.opam/5.0/.opam-switch/build/dns.5.0.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dns -j 31
 exit-code            1
 env-file             ~/.opam/log/dns-8-983f73.env
 output-file          ~/.opam/log/dns-8-983f73.out
output ###
 File "cache/dns_cache.ml", line 98, characters 13-41:
 98 | module LRU = Lru.M.MakeSeeded(Key)(Entry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 Error: The functor application is ill-typed.
        These arguments:
          Key Entry
        do not match these parameters:
          functor (K : Hashtbl.SeededHashedType) (V : Lru.Weighted) -> ...
        1. Modules do not match:
             Key :
             sig
               type t = [ `raw ] Domain_name.t
               val equal : 'a Domain_name.t -> 'b Domain_name.t -> bool
               val hash : int -> 'a -> int
             end
           is not included in
             Hashtbl.SeededHashedType
           The value `seeded_hash' is required but not provided
           File "hashtbl.mli", line 399, characters 4-36: Expected declaration
        2. Module Entry matches the expected module type Lru.Weighted