git: conflict with cmdliner>=1.0 if git-unix is active
fails with
```
  File "bin/ogit.ml", line 90, characters 19-23:
  Error: This expression has type
           ?docv:string ->
           (string -> ('a, [ `Msg of string ]) result) * 'a printer ->
           'a converter
         but an expression was expected of type
           'b converter = 'b parser * 'b printer
  Command exited with code 2.
```