jingoo 1.2.16-1.2.19 are not compatible with ocaml-5
Use String.uppercase

```
=== ERROR while compiling jingoo.1.2.18 ======================================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.0/.opam-switch/build/jingoo.1.2.18
 command              ~/.opam/opam-init/hooks/sandbox.sh build make
 exit-code            2
 env-file             ~/.opam/log/jingoo-7-326b08.env
 output-file          ~/.opam/log/jingoo-7-326b08.out
 make -C src
 make[1]: Entering directory '/home/opam/.opam/5.0/.opam-switch/build/jingoo.1.2.18/src'
 ocamlyacc jg_parser.mly
 1 rule never reduced
 230 shift/reduce conflicts, 121 reduce/reduce conflicts.
 ocamllex jg_lexer.mll
 230 states, 11598 transitions, table size 47772 bytes
 ocamlfind ocamlc -g -package unix,dynlink,pcre,uutf -c jg_types.mli jg_types.ml jg_utils.ml jg_stub.mli jg_stub.ml jg_parser.mli jg_parser.ml jg_lexer.ml jg_runtime.ml jg_interp.ml jg_template.mli jg_template.ml
 File "jg_runtime.ml", line 281, characters 16-32:
 281 |     | _ -> (try Jg_stub.get_func obj_name prop_name with Not_found -> Tnull)
                       ^^^^^^^^^^^^^^^^
 Warning 6 [labels-omitted]: labels namespace, func_name were omitted in the application of this function.
 File "jg_runtime.ml", line 598, characters 24-40:
 598 |     | Tstr str -> Tstr (String.uppercase str)
                               ^^^^^^^^^^^^^^^^
 Error: Unbound value String.uppercase
 make[1]: *** [Makefile:36: jingoo.cma] Error 2
 make[1]: Leaving directory '/home/opam/.opam/5.0/.opam-switch/build/jingoo.1.2.18/src'
 make: *** [Makefile:0: all] Error 2
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>