zipperposition: upper bound on containers
due to
```
 File "src/core/Interfaces.ml", line 13, characters 22-34:
 Error: Unbound type constructor CCHash.state
```