otel-cohttp-lwt fix compat error
=== ERROR while compiling opentelemetry-cohttp-lwt.0.12 ======================#
 context              2.5.0 | linux/x86_64 | ocaml-base-compiler.5.4.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.4/.opam-switch/build/opentelemetry-cohttp-lwt.0.12
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p opentelemetry-cohttp-lwt -j 255 --promote-install-files=false @install
 exit-code            1
 env-file             ~/.opam/log/opentelemetry-cohttp-lwt-7-19a1d3.env
 output-file          ~/.opam/log/opentelemetry-cohttp-lwt-7-19a1d3.out
=== output ===
 (cd _build/default && /home/opam/.opam/5.4/bin/ocamlc.opt -w -40 -warn-error -a+8 -w +a-4-30-40-41-42-44-48-70 -strict-sequence -g -bin-annot -bin-annot-occurrences -I src/integrations/cohttp/.opentelemetry_cohttp_lwt.objs/byte -I /home/opam/.opam/5.4/lib/angstrom -I /home/opam/.opam/5.4/lib/atomic -I /home/opam/.opam/5.4/lib/base64 -I /home/opam/.opam/5.4/lib/bigstringaf -I /home/opam/.opam/5.4/lib/cohttp -I /home/opam/.opam/5.4/lib/cohttp-lwt -I /home/opam/.opam/5.4/lib/domain-name -I /home/opam/.opam/5.4/lib/hmap -I /home/opam/.opam/5.4/lib/http -I /home/opam/.opam/5.4/lib/ipaddr -I /home/opam/.opam/5.4/lib/logs -I /home/opam/.opam/5.4/lib/logs/lwt -I /home/opam/.opam/5.4/lib/lwt -I /home/opam/.opam/5.4/lib/macaddr -I /home/opam/.opam/5.4/lib/ocaml/threads -I /home/opam/.opam/5.4/lib/ocaml/unix -I /home/opam/.opam/5.4/lib/opentelemetry -I /home/opam/.opam/5.4/lib/opentelemetry-lwt -I /home/opam/.opam/5.4/lib/opentelemetry/ambient-context -I /home/opam/.opam/5.4/lib/opentelemetry/ambient-context/types -I /home/opam/.opam/5.4/lib/opentelemetry/atomic -I /home/opam/.opam/5.4/lib/opentelemetry/proto -I /home/opam/.opam/5.4/lib/pbrt -I /home/opam/.opam/5.4/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.4/lib/ptime -I /home/opam/.opam/5.4/lib/ptime/clock -I /home/opam/.opam/5.4/lib/re -I /home/opam/.opam/5.4/lib/sexplib0 -I /home/opam/.opam/5.4/lib/stringext -I /home/opam/.opam/5.4/lib/thread-local-storage -I /home/opam/.opam/5.4/lib/uri -I /home/opam/.opam/5.4/lib/uri-sexp -I /home/opam/.opam/5.4/lib/uri/services -no-alias-deps -o src/integrations/cohttp/.opentelemetry_cohttp_lwt.objs/byte/opentelemetry_cohttp_lwt.cmo -c -impl src/integrations/cohttp/opentelemetry_cohttp_lwt.ml)
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 233, characters 10-16:
 233 |   (module Traced : Cohttp_lwt.S.Client)
                 ^^^^^^
 Error: Signature mismatch:
        ...
        The module IO is required but not provided
        File "cohttp-lwt/src/s.ml", line 196, characters 2-42:
          Expected declaration