regular: upper bound on core_kernel
due to interface change:

```
 File "lib/regular/regular_bytes.ml", line 64, characters 18-21:
 Error: Signature mismatch:
       ...
       The value `unsafe_blit' is required but not provided
       The value `length' is required but not provided
       The value `create' is required but not provided
```