cohttp_async_websocket need cohttp < 6
check.ci.ocaml.org tries to install cohttp-async.6.0.0~beta2 and gets an
error:

````
 Error: Modules do not match:
        sig
          module IO = Cohttp_async__Io.IO
          module Request = Cohttp_async.Io.Request
          module Response = Cohttp_async.Io.Response
        end
      is not included in Cohttp__.S.IO
      The type "t" is required but not provided
      File "cohttp/src/s.ml", line 23, characters 2-12: Expected declaration
      The value ">>=" is required but not provided
````

I beleive version constraints were setup incorreclty before:

````
➜  ~ dpkg --compare-versions 6.0.0~beta2  lt 6 && echo true || echo false
false
➜  ~ dpkg --compare-versions 6.0.0~beta2  lt 6.0.0 && echo true || echo false
true
````

Signed-off-by: Kakadu <kakadu.hafanana@gmail.com>