Avoid building on 32 bit architectures
Fails to build because it uses unrepresentable literals on any 32 bit
architecture:

> File "datalog/utils.ml", line 36, characters 13-23:
> 36 |   let seed = 0x9747b28c in
>                   ^^^^^^^^^^
> Error: Integer literal exceeds the range of representable integers of type int
> Command exited with code 2.
> make: *** [Makefile:20: prod] Error 10