h2 0.8.0 is not compatible with ocaml 5, noticed in #22358
=== ERROR while compiling h2.0.8.0 ===========================================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.0.0+trunk | file:///home/opam/opam-repository
 path                 ~/.opam/5.0/.opam-switch/build/h2.0.8.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p h2 -j 31
 exit-code            1
 env-file             ~/.opam/log/h2-8-fe5388.env
 output-file          ~/.opam/log/h2-8-fe5388.out
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.h2.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/faraday -I /home/opam/.opam/5.0/lib/hpack -I /home/opam/.opam/5.0/lib/httpaf -I /home/opam/.opam/5.0/lib/psq -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -no-alias-deps -open H2__ -o lib/.h2.objs/byte/h2__Scheduler.cmo -c -impl lib/scheduler.ml)
 File "lib/scheduler.ml", lines 34-40, characters 10-6:
 34 | ..........Hashtbl.MakeSeeded (struct
 35 |     type t = Stream_identifier.t
 36 |
 37 |     let equal = Stream_identifier.( === )
 38 |
 39 |     let hash i k = Hashtbl.seeded_hash i k
 40 |   end)
 Error: Modules do not match:
        sig
          type t = H2__.Stream_identifier.t
          val equal : Int32.t -> Int32.t -> bool
          val hash : int -> 'a -> int
        end
      is not included in Hashtbl.SeededHashedType
      The value `seeded_hash' is required but not provided
      File "hashtbl.mli", line 399, characters 4-36: Expected declaration