qcheck-core: add lower bounds on alcotest
They use `check'` introduced in 1.2.0

```
=== ERROR while compiling qcheck-core.0.21.3 =================================#
 context              2.2.0~rc1~dev | linux/x86_64 | ocaml-base-compiler.5.2.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.2/.opam-switch/build/qcheck-core.0.21.3
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p qcheck-core -j 31
 exit-code            1
 env-file             ~/.opam/log/qcheck-core-7-f16eb0.env
 output-file          ~/.opam/log/qcheck-core-7-f16eb0.out
 (cd _build/default && /home/opam/.opam/5.2/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I test/core/.QCheck_unit_tests.eobjs/byte -I /home/opam/.opam/5.2/lib/alcotest -I /home/opam/.opam/5.2/lib/astring -I /home/opam/.opam/5.2/lib/bytes -I /home/opam/.opam/5.2/lib/cmdliner -I /home/opam/.opam/5.2/lib/fmt -I /home/opam/.opam/5.2/lib/ocaml/unix -I /home/opam/.opam/5.2/lib/re -I /home/opam/.opam/5.2/lib/seq -I /home/opam/.opam/5.2/lib/stdlib-shims -I /home/opam/.opam/5.2/lib/uuidm -I src/core/.qcheck_core.objs/byte -no-alias-deps -open Dune__exe -o test/core/.QCheck_unit_tests.eobjs/byte/dune__exe__QCheck2_unit_tests.cmo -c -impl test/core/QCheck2_unit_tests.ml)
 File "test/core/QCheck2_unit_tests.ml", line 23, characters 14-20:
 23 |     Alcotest.(check' (list int))
                    ^^^^^^
 Error: Unbound value "check'"
 Hint: Did you mean "check"?
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>