Inquire need OCaml < 5.2
Compilation error:

>  ansi_stubs.c:45:36: error: implicit declaration of function 'failwith'; did you mean 'caml_failwith'? [-Wimplicit-function-declaration]
    45 |   if (ioctl(fd, TIOCGWINSZ, &win)) failwith("Ansi.size");

These function were renamed near OCaml 5.1: https://github.com/ocaml/ocaml/blob/5.1.1/Changes#L1035

Signed-off-by: Kakadu <kakadu.hafanana@gmail.com>