all jupyter versions are incompatible with OCaml 4.08.0
```
File "compat.cppo.ml", line 58, characters 40-52:
Error: The field Location.loc belongs to the record type Location.loc
       but a field was expected belonging to the record type
         Location.error = Location.report
```

This code was added before the first release of jupyter, and relies on
the definition of Location.error which has changed in 4.08.