unix-fcntl doesn't build with 4.05.0, which introduces O_KEEPEXEC:
    File "unix/fcntl_unix.ml", line 58, characters 28-516:
    Warning 8: this pattern-matching is not exhaustive.
    Here is an example of a case that is not matched:
    O_KEEPEXEC
    File "unix/fcntl_unix.ml", line 1:
    Error: Some fatal warnings were triggered (1 occurrences)
    Command exited with code 2.
    Makefile:77: recipe for target 'build' failed