guardian depends on the result library
```
=== ERROR while compiling guardian.0.1.0 =====================================#
 context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/guardian.0.1.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p guardian -j 31 --promote-install-files=false @install
 exit-code            1
 env-file             ~/.opam/log/guardian-7-f51419.env
 output-file          ~/.opam/log/guardian-7-f51419.out
 File "lib/dune", line 5, characters 32-38:
 5 |  (libraries containers logs lwt result uuidm)
                                     ^^^^^^
 Error: Library "result" not found.
 -> required by library "guardian" in _build/default/lib
 -> required by _build/default/META.guardian
 -> required by _build/install/default/lib/guardian/META
 -> required by _build/default/guardian.install
 -> required by alias install
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>