Update opam
Due to

```
# File "ppx-driver/gen_js_api_ppx_driver.ml", line 22, characters 4-39:
# 22 |     Ppxlib.Driver.enable_location_check ()
#          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Ppxlib.Driver.enable_location_check
```