clangml and pyml are not compatible with stdcompat >= 21
Seen on https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2816ad4dba16196f57cd1f9363ca75af4a4fa046 from PR #28305

The new stdcompat does no longer ship the headers:
fatal error: stdcompat.h: No such file or directory

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>