safemoney, sarif: dependency on ppx_expect
They all fail with a variation of
```
=== ERROR while compiling safemoney.0.1.1 ====================================#
 context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.5.2.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.2/.opam-switch/build/safemoney.0.1.1
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p safemoney -j 255 @install @runtest
 exit-code            1
 env-file             ~/.opam/log/safemoney-7-875a72.env
 output-file          ~/.opam/log/safemoney-7-875a72.out
 File "test/dune", line 3, characters 43-60:
 3 |  (libraries safemoney_lib base core zarith ppx_expect.common ppx_expect.config ppx_expect.config_types stdint angstrom yojson)
                                                ^^^^^^^^^^^^^^^^^
 Error: Library "ppx_expect.common" not found.
 -> required by library "safemoney_test" in _build/default/test
 -> required by
    _build/default/test/.safemoney_test.inline-tests/inline_test_runner_safemoney_test.exe
 -> required by alias test/runtest in test/dune:4
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>