ocaml-twt is not compatible with ocaml5, uses stream
Error:
```
\#=== ERROR while installing ocaml-twt.0.94.0 ==================================#
\# context              2.2.0~alpha3~dev | linux/x86_64 | ocaml-base-compiler.5.1.0 | file:///home/opam/opam-repository
\# path                 ~/.opam/5.1/.opam-switch/build/ocaml-twt.0.94.0
\# command              ~/.opam/opam-init/hooks/sandbox.sh install make install PREFIX=/home/opam/.opam/5.1
\# exit-code            2
\# env-file             ~/.opam/log/ocaml-twt-7-3b74fc.env
\# output-file          ~/.opam/log/ocaml-twt-7-3b74fc.out
\### output ###
\# ocamlc -o ocaml+twt str.cma unix.cma ocaml+twt.ml
\# File "ocaml+twt.ml", line 1:
\# Warning 24 [bad-module-name]: bad source file name: "Ocaml+twt" is not a valid module name.
\#
\# File "_none_", line 1:
\# Alert ocaml_deprecated_auto_include:
\# OCaml's lib directory layout changed in 5.0. The str subdirectory has been
\# automatically added to the search path, but you should add -I +str to the
\# command-line to silence this alert (e.g. by adding str to the list of
\# libraries in your dune file, or adding use_str to your _tags file for
\# ocamlbuild, or using -package str for ocamlfind).
\#
\# File "ocaml+twt.ml", line 390, characters 15-29:
\# 390 |   let stream = Stream.of_list lines in
\#                      ^^^^^^^^^^^^^^
\# Error: Unbound module Stream
\# make: *** [Makefile:7: ocaml+twt] Error 2

```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>