biocaml: upper bound on solvuu-build due to api change
otherwise build fails with

```
 Error: The function applied to this argument has type
 [...]
          ?linkall:unit ->
          ?mli_files:[ `Add of string list | `Replace of string list ] ->
          ?c_files:[ `Add of string list | `Replace of string list ] ->
          ?h_files:[ `Add of string list | `Replace of string list ] ->
          ?install:[ `Findlib of Solvuu_build.Std.Project.findlib_pkg | `No ] ->
          Solvuu_build.Project.item
 This argument cannot be applied with label ~pkg
```