fat-filesystem requires result
Fails with
```
=== ERROR while compiling fat-filesystem.0.13.0 ==============================#
 context              2.2.0~alpha3 | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/fat-filesystem.0.13.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p fat-filesystem -j 71
 exit-code            1
 env-file             ~/.opam/log/fat-filesystem-7-176cf6.env
 output-file          ~/.opam/log/fat-filesystem-7-176cf6.out
 File "src/dune", line 5, characters 3-9:
 5 |    result rresult astring)
        ^^^^^^
 Error: Library "result" not found.
 -> required by library "fat-filesystem" in _build/default/src
 -> required by _build/default/META.fat-filesystem
 -> required by _build/install/default/lib/fat-filesystem/META
 -> required by _build/default/fat-filesystem.install
 -> required by alias install
```
Signed-off-by: Marcello Seri <marcello.seri@gmail.com>