opentelemetry-cohttp-lwt is not compatible with new cohttp
Fails with
```
File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 231, characters 10-16:
231 |   (module Traced : Cohttp_lwt.S.Client)
                ^^^^^^
Error: Signature mismatch:
       ...
       The value `set_cache' is required but not provided
       File "cohttp-lwt/src/s.ml", line 190, characters 2-30:
         Expected declaration
```
Signed-off-by: Marcello Seri <marcello.seri@gmail.com>