Restrict dolmne.0.4.1 from building on OCaml 5
FTBFS due to missing `Pervasives`:

    #=== ERROR while compiling dolmen.0.4.1 =======================================#
    # context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
    # path                 ~/.opam/5.0/.opam-switch/build/dolmen.0.4.1
    # command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dolmen -j 127
    # exit-code            1
    # env-file             ~/.opam/log/dolmen-8-1816f7.env
    # output-file          ~/.opam/log/dolmen-8-1816f7.out
    ### output ###
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/standard/.dolmen_std.objs/byte -I /home/opam/.opam/5.0/lib/menhirLib -I src/interface/.dolmen_intf.objs/byte -I src/languages/line/.dolmen_line.objs/byte -intf-suffix .ml -no-alias-deps -open Dolmen_std -o src/standard/.dolmen_std.objs/byte/dolmen_std__Id.cmo -c -impl src/standard/id.ml)
    # File "src/standard/id.ml", line 18, characters 14-32:
    # 18 | let compare = Pervasives.compare
    #                    ^^^^^^^^^^^^^^^^^^
    # Error: Unbound module Pervasives
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I src/standard/.dolmen_std.objs/byte -I src/standard/.dolmen_std.objs/native -I /home/opam/.opam/5.0/lib/menhirLib -I src/interface/.dolmen_intf.objs/byte -I src/interface/.dolmen_intf.objs/native -I src/languages/line/.dolmen_line.objs/byte -I src/languages/line/.dolmen_line.objs/native -intf-suffix .ml -no-alias-deps -open Dolmen_std -o src/standard/.dolmen_std.objs/native/dolmen_std__Id.cmx -c -impl src/standard/id.ml)
    # File "src/standard/id.ml", line 18, characters 14-32:
    # 18 | let compare = Pervasives.compare
    #                    ^^^^^^^^^^^^^^^^^^
    # Error: Unbound module Pervasives
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/standard/.dolmen_std.objs/byte -I /home/opam/.opam/5.0/lib/menhirLib -I src/interface/.dolmen_intf.objs/byte -I src/languages/line/.dolmen_line.objs/byte -intf-suffix .ml -no-alias-deps -open Dolmen_std -o src/standard/.dolmen_std.objs/byte/dolmen_std__Term.cmo -c -impl src/standard/term.ml)
    # File "src/standard/term.ml", line 205, characters 29-47:
    # 205 |   | Builtin b, Builtin b' -> Pervasives.compare b b'
    #                                    ^^^^^^^^^^^^^^^^^^
    # Error: Unbound module Pervasives