caravan: add upper bound to ocaml version due to Result warning
warnings-as-errors;
```
Warning 45: this open statement shadows the constructor Error (which is later used)
File "src/caravan/caravan.ml", line 1:
Error: Some fatal warnings were triggered (2 occurrences)
```