soupault 2.3+ needs base64 > 3
Due to 
```
(cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.soupault.eobjs/byte -I /home/opam/.opam/4.08/lib/ISO8601 -I /home/opam/.opam/4.08/lib/base64 -I /home/opam/.opam/4.08/lib/bytes -I /home/opam/.opam/4.08/lib/containers -I /home/opam/.opam/4.08/lib/containers/monomorphic -I /home/opam/.opam/4.08/lib/cstruct -I /home/opam/.opam/4.08/lib/ezjsonm -I /home/opam/.opam/4.08/lib/fileutils -I /home/opam/.opam/4.08/lib/fmt -I /home/opam/.opam/4.08/lib/hex -I /home/opam/.opam/4.08/lib/jingoo -I /home/opam/.opam/4.08/lib/jsonm -I /home/opam/.opam/4.08/lib/lambdasoup -I /home/opam/.opam/4.08/lib/logs -I /home/opam/.opam/4.08/lib/lua-ml -I /home/opam/.opam/4.08/lib/markup -I /home/opam/.opam/4.08/lib/ocplib-endian -I /home/opam/.opam/4.08/lib/odate -I /home/opam/.opam/4.08/lib/ppx_deriving/runtime -I /home/opam/.opam/4.08/lib/re -I /home/opam/.opam/4.08/lib/result -I /home/opam/.opam/4.08/lib/seq -I /home/opam/.opam/4.08/lib/sexplib -I /home/opam/.opam/4.08/lib/sexplib/0 -I /home/opam/.opam/4.08/lib/spelll -I /home/opam/.opam/4.08/lib/stringext -I /home/opam/.opam/4.08/lib/toml -I /home/opam/.opam/4.08/lib/tsort -I /home/opam/.opam/4.08/lib/uchar -I /home/opam/.opam/4.08/lib/uucp -I /home/opam/.opam/4.08/lib/uutf -no-alias-deps -open Dune__exe -o src/.soupault.eobjs/byte/dune__exe__Plugin_api.cmo -c -impl src/plugin_api.ml)
File "src/plugin_api.ml", line 467, characters 16-33:
467 |       try Some (Base64.decode_exn s)
                      ^^^^^^^^^^^^^^^^^
Error: Unbound value Base64.decode_exn
```