snappy 0.0.1 seems unbuildable
I can reproduce the build error from the CI on my machine:

```
$ ocamlfind ocamlopt -g -I src -linkpkg -I src src/snappy.cmxa test.cmx -o test.native
/usr/bin/ld: src/libsnappy_stubs.a(snappy_stubs.o): undefined reference to symbol '_ZTISt9exception@@GLIBCXX_3.4'
//usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
Command exited with code 2.
```