Mark unavailable on Windows
The package uses `glob.h` which is POSIX-exclusive and not available on
Windows.

Failing build: https://github.com/ocaml/opam-repository/actions/runs/14517357396/job/40729513622?pr=27778

Relevant output:

=== ERROR while compiling globlon.1.0 ========================================#
 context     2.3.0 | win32/x86_64 | ocaml.5.3.0 | file://D:/a/opam-repository/opam-repository
 path        D:\opamroot\default\.opam-switch\build\globlon.1.0
 command     D:\opamroot\default\bin\dune.exe build -p globlon -j 3 @install
 exit-code   1
 env-file    D:\opamroot\log\globlon-7784-2e5e3a.env
 output-file D:\opamroot\log\globlon-7784-2e5e3a.out
;## output ###
 File "lib/dune", line 6, characters 9-13:
 6 |   (names glob)))
              ^^^^
 (cd _build/default/lib && D:\opamroot\default\bin\x86_64-w64-mingw32-gcc.exe -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -O2 -fno-strict-aliasing -fwrapv -mms-bitfields -g -I D:/opamroot/default/lib/ocaml -o glob.o -c glob.c)
 glob.c:1:10: fatal error: glob.h: No such file or directory
     1 | #include <glob.h>
       |          ^~~~~~~~
 compilation terminated.