mirage-crypto-pk 0.6* 0.7* 0.8.0: restrict to eqaf < 0.10
```
=== ERROR while compiling mirage-crypto-pk.0.8.0 =============================#
 context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/mirage-crypto-pk.0.8.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p mirage-crypto-pk -j 255
 exit-code            1
 env-file             ~/.opam/log/mirage-crypto-pk-7-5cecb4.env
 output-file          ~/.opam/log/mirage-crypto-pk-7-5cecb4.out
 ## output ###
 File "pk/dune", line 4, characters 68-80:
 4 |   (libraries cstruct zarith mirage-crypto mirage-crypto-rng sexplib eqaf.cstruct rresult)
                                                                         ^^^^^^^^^^^^
 Error: Library "eqaf.cstruct" not found.
 -> required by library "mirage-crypto-pk" in _build/default/pk
 -> required by _build/default/META.mirage-crypto-pk
 -> required by _build/install/default/lib/mirage-crypto-pk/META
 -> required by _build/default/mirage-crypto-pk.install
 -> required by alias install
```