yaml: add conflict with old version of result
This fixes:

```
-     ocamlopt unix/.yaml_unix.objs/native/yaml_unix.{cmx,o} (exit 2)
- (cd _build/default && /home/opam/.opam/4.13/bin/ocamlopt.opt -w -40 -w -9-27-32 -g -I unix/.yaml_unix.objs/byte -I unix/.yaml_unix.objs/native -I /home/opam/.opam/4.13/lib/astring -I /home/opam/.opam/4.13/lib/bos -I /home/opam/.opam/4.13/lib/bytes -I /home/opam/.opam/4.13/lib/ctypes -I /home/opam/.opam/4.13/lib/fmt -I /home/opam/.opam/4.13/lib/fpath -I /home/opam/.opam/4.13/lib/integers -I /home/opam/.opam/4.13/lib/logs -I /home/opam/.opam/4.13/lib/result -I /home/opam/.opam/4.13/lib/rresult -I ffi/bindings/.yaml_bindings.objs/byte -I ffi/bindings/.yaml_bindings.objs/native -I ffi/lib/.yaml_ffi.objs/byte -I ffi/lib/.yaml_ffi.objs/native -I lib/.yaml.objs/byte -I lib/.yaml.objs/native -I types/bindings/.yaml_bindings_types.objs/byte -I types/bindings/.yaml_bindings_types.objs/native -I types/lib/.yaml_types.objs/byte -I types/lib/.yaml_types.objs/native -I vendor/.yaml_c.objs/byte -I vendor/.yaml_c.objs/native -intf-suffix .ml -no-alias-deps -o unix/.yaml_unix.objs/native/yaml_unix.cmx -c -impl unix/yaml_unix.ml)
- File "unix/yaml_unix.ml", line 17, characters 16-27:
- 17 | let of_file f = Result.bind (OS.File.read f) Yaml.of_string
-                      ^^^^^^^^^^^
- Error: Unbound value Result.bind
```