text-tags: upper bound on core_kernel
due to interface changes in core_kernel

```
 File "lib/text_tags/text_tags.ml", line 176, characters 2-29:
 Error: This expression has type equal:(mode -> mode -> bool) -> 'a option
        but an expression was expected of type ('b -> 'c) option
```