ahrocksdb: fix lower bounds
dune-project file requires dune 1.3 and ctypes needs to be 0.13.0 due to
```
#=== ERROR while compiling ahrocksdb.0.2.1 ====================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://github.com/ahrefs/ocaml-ahrocksdb/releases/download/0.2.1/ahrocksdb-0.2.1.tbz)
# path                 ~/.opam/4.08/.opam-switch/build/ahrocksdb.0.2.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ahrocksdb -j 71
# exit-code            1
# env-file             ~/.opam/log/ahrocksdb-7-231d82.env
# output-file          ~/.opam/log/ahrocksdb-7-231d82.out
### output ###
#       ocamlc ffi/structs/.rocksdb_types.objs/rocksdb_types.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -g -bin-annot -I ffi/structs/.rocksdb_types.objs -I ffi/structs/.rocksdb_types.objs/.private -I /home/opam/.opam/4.08/lib/bytes -I /home/opam/.opam/4.08/lib/ctypes -I /home/opam/.opam/4.08/lib/integers -no-alias-deps -o ffi/structs/.rocksdb_types.objs/rocksdb_types.cmo -c -impl ffi/structs/rocksdb_types.ml)
# File "ffi/structs/rocksdb_types.ml", line 1, characters 24-35:
# 1 | module Struct_stubs(S : Ctypes.TYPE) = struct
#                             ^^^^^^^^^^^
# Error: Unbound module type Ctypes.TYPE
```