some versions of elpi are not compatible with ocaml 5
Error:
```
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/utils/.elpi_util.objs/byte -I /home/opam/.opam/5.0/lib/re -I /home/opam/.opam/5.0/lib/re/str -I /home/opam/.opam/5.0/lib/seq -intf-suffix .ml -no-alias-deps -open Elpi_util -o src/utils/.elpi_util.objs/byte/elpi_util__Util.cmo -c -impl src/utils/util.ml)
 File "_none_", line 1:
 Alert ocaml_deprecated_auto_include:
 OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
 automatically added to the search path, but you should add -I +unix to the
 command-line to silence this alert (e.g. by adding unix to the list of
 libraries in your dune file, or adding use_unix to your _tags file for
 ocamlbuild, or using -package unix for ocamlfind).
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I src/utils/.elpi_util.objs/byte -I src/utils/.elpi_util.objs/native -I /home/opam/.opam/5.0/lib/re -I /home/opam/.opam/5.0/lib/re/str -I /home/opam/.opam/5.0/lib/seq -intf-suffix .ml -no-alias-deps -open Elpi_util -o src/utils/.elpi_util.objs/native/elpi_util__Util.cmx -c -impl src/utils/util.ml)
 File "_none_", line 1:
 Alert ocaml_deprecated_auto_include:
 OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
 automatically added to the search path, but you should add -I +unix to the
 command-line to silence this alert (e.g. by adding unix to the list of
 libraries in your dune file, or adding use_unix to your _tags file for
 ocamlbuild, or using -package unix for ocamlfind).
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.elpi.objs/byte -I src/.elpi.objs/public_cmi -I /home/opam/.opam/5.0/lib/menhirLib -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ppx_deriving/runtime -I /home/opam/.opam/5.0/lib/re -I /home/opam/.opam/5.0/lib/re/str -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/stdlib-shims -I src/parser/.elpi_lexer_config.objs/byte -I src/parser/.elpi_parser.objs/byte -I src/utils/.elpi_util.objs/byte -I trace/runtime/.trace_ppx_runtime.objs/byte -no-alias-deps -open Elpi__ -o src/.elpi.objs/byte/elpi__Data.cmo -c -impl src/data.pp.ml)
 File "src/data.ml", line 655, characters 14-28:
 655 |         (Obj.(extension_name (extension_constructor x)))
                     ^^^^^^^^^^^^^^
 Error: Unbound value extension_name
 make: *** [Makefile:40: build] Error 1
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>