Do not run tests for re.1.{9.0,10.3} on OCaml 5
Tests fails due to removed function `String.capitalize`:

    #=== ERROR while compiling re.1.10.3 ==========================================#
    # context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
    # path                 ~/.opam/5.0/.opam-switch/build/re.1.10.3
    # command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p re -j 127
    # exit-code            1
    # env-file             ~/.opam/log/re-8-05e108.env
    # output-file          ~/.opam/log/re-8-05e108.out
    ### output ###
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -w -50 -g -bin-annot -I lib_test/.test_easy.eobjs/byte -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/oUnit -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ounit2 -I /home/opam/.opam/5.0/lib/ounit2/advanced -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/stdlib-shims -I lib/.re.objs/byte -I lib_test/fort_unit/.fort_unit.objs/byte -no-alias-deps -open Dune__exe -o lib_test/.test_easy.eobjs/byte/dune__exe__Test_easy.cmo -c -impl lib_test/test_easy.ml)
    # File "lib_test/test_easy.ml", line 7, characters 27-44:
    # 7 |   let capitalize_ascii   = String.capitalize
    #                                ^^^^^^^^^^^^^^^^^
    # Error: Unbound value String.capitalize

and

    #=== ERROR while compiling re.1.9.0 ===========================================#
    # context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
    # path                 ~/.opam/5.0/.opam-switch/build/re.1.9.0
    # command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p re -j 31
    # exit-code            1
    # env-file             ~/.opam/log/re-6-464d68.env
    # output-file          ~/.opam/log/re-6-464d68.out
    ### output ###
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -w -50 -g -bin-annot -I lib_test/.test_easy.eobjs/byte -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/oUnit -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/ounit2 -I /home/opam/.opam/5.0/lib/ounit2/advanced -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/stdlib-shims -I lib/.re.objs/byte -I lib_test/fort_unit/.fort_unit.objs/byte -no-alias-deps -o lib_test/.test_easy.eobjs/byte/test_easy.cmo -c -impl lib_test/test_easy.ml)
    # File "lib_test/test_easy.ml", line 7, characters 27-44:
    # 7 |   let capitalize_ascii   = String.capitalize
    #                                ^^^^^^^^^^^^^^^^^
    # Error: Unbound value String.capitalize