soupault 2.{0,1} needs updated jingo lower bound
Due to
```
File "src/template.ml", line 3, characters 9-29:
3 | type t = Jg_template.Loaded.t
             ^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Jg_template.Loaded
```