rtop: add lower bound on reason
Fixes the following failure:

```
#=== ERROR while compiling rtop.3.7.0 =========================================#
# context     2.1.0 | linux/x86_64 | ocaml-base-compiler.4.08.1 | https://opam.ocaml.org#8f2ba337
# path        ~/git/ocaml/cql-ppx/_opam/.opam-switch/build/rtop.3.7.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p rtop -j 9
# exit-code   1
# env-file    ~/.opam/log/rtop-24818-2eb0f0.env
# output-file ~/.opam/log/rtop-24818-2eb0f0.out
### output ###
#       ocamlc src/reason-parser-tests/.testOprint.eobjs/byte/testOprint.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/vagrant/git/ocaml/cql-ppx/_opam/bin/ocamlc.opt -w -40 -g -bin-annot -I src/reason-parser-tests/.testOprint.eobjs/byte -I /home/vagrant/git/ocaml/cql-ppx/_opam/lib/menhirLib -I /home/vagrant/git/ocaml/cql-ppx/_opam/lib/ocaml-migrate-parsetree -I /home/vagrant/git/ocaml/cql-ppx/_opam/lib/ocaml/compiler-libs -I /home/vagrant/git/ocaml/cql-ppx/_opam/lib/ppx_derivers -I[...]
# File "testOprint.cppo.ml", line 22, characters 5-29:
# Error: Unbound module Reason_migrate_parsetree
# File "src/rtop/dune", line 7, characters 74-104:
# 7 |  (libraries compiler-libs.common menhirLib reason.easy_format reason utop reason.ocaml-migrate-parsetree))
#                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "reason.ocaml-migrate-parsetree" not found.
# Hint: try:
#   dune external-lib-deps --missing -p rtop -j 9 @install
```