fiat-p256 0.2* does not compile with eqaf 0.10
```
=== ERROR while compiling fiat-p256.0.2.1 ====================================#
 context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/fiat-p256.0.2.1
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p fiat-p256 -j 255
 exit-code            1
 env-file             ~/.opam/log/fiat-p256-7-227f51.env
 output-file          ~/.opam/log/fiat-p256-7-227f51.out
 ## output ###
 File "p256/dune", line 4, characters 36-48:
 4 |  (libraries bigarray-compat cstruct eqaf.cstruct hex)
                                         ^^^^^^^^^^^^
 Error: Library "eqaf.cstruct" not found.
 -> required by library "fiat-p256" in _build/default/p256
 -> required by _build/default/META.fiat-p256
 -> required by _build/install/default/lib/fiat-p256/META
 -> required by _build/default/fiat-p256.install
 -> required by alias install
```