tensorflow: older versions have an upper bound on core_kernel
due to

```
 File "src/graph/node.ml", line 137, characters 14-30:
 Error: This expression has type
          equal:(string -> string -> bool) -> attr option
        but an expression was expected of type
          'a Core_kernel.Std.Option.t = 'a option
```