webmachine 0.5.0 uses bytes
Fails with
```
=== ERROR while compiling webmachine.0.5.0 ===================================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/webmachine.0.5.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build jbuilder build -p webmachine -j 71
 exit-code            1
 env-file             ~/.opam/log/webmachine-7-806cc7.env
 output-file          ~/.opam/log/webmachine-7-806cc7.out
\## output ###
 File "/home/opam/.opam/4.14/lib/cohttp/META", line 1, characters 0-0:
 Error: Library "bytes" not found.
 -> required by library "cohttp" in /home/opam/.opam/4.14/lib/cohttp
 Hint: try: jbuilder external-lib-deps --missing -p webmachine @install
```
Signed-off-by: Marcello Seri <marcello.seri@gmail.com>