opentelemetry is not compatible with cohttp 6
Failure:
```
=== ERROR while compiling opentelemetry-cohttp-lwt.0.4 =======================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.0/.opam-switch/build/opentelemetry-cohttp-lwt.0.4
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p opentelemetry-cohttp-lwt -j 47 @install
 exit-code            1
 env-file             ~/.opam/log/opentelemetry-cohttp-lwt-7-94a143.env
 output-file          ~/.opam/log/opentelemetry-cohttp-lwt-7-94a143.out
 (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -warn-error -a+8 -strict-sequence -g -bin-annot -I src/integrations/cohttp/.opentelemetry_cohttp_lwt.objs/byte -I /home/opam/.opam/5.0/lib/angstrom -I /home/opam/.opam/5.0/lib/base64 -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/cohttp -I /home/opam/.opam/5.0/lib/cohttp-lwt -I /home/opam/.opam/5.0/lib/http -I /home/opam/.opam/5.0/lib/logs -I /home/opam/.opam/5.0/lib/lwt -I /home/opam/.opam/5.0/lib/ocaml/threads -I /home/opam/.opam/5.0/lib/ocaml/unix -I /home/opam/.opam/5.0/lib/opentelemetry -I /home/opam/.opam/5.0/lib/opentelemetry-lwt -I /home/opam/.opam/5.0/lib/opentelemetry/atomic -I /home/opam/.opam/5.0/lib/pbrt -I /home/opam/.opam/5.0/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/ptime/clock/os -I /home/opam/.opam/5.0/lib/re -I /home/opam/.opam/5.0/lib/seq -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/stringext -I /home/opam/.opam/5.0/lib/uri -I /home/opam/.opam/5.0/lib/uri-sexp -no-alias-deps -o src/integrations/cohttp/.opentelemetry_cohttp_lwt.objs/byte/opentelemetry_cohttp_lwt.cmo -c -impl src/integrations/cohttp/opentelemetry_cohttp_lwt.ml)
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 65, characters 30-39:
 65 |   let attrs_of_request (req : Request.t) =
                                    ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 66, characters 22-34:
 66 |     let meth = req |> Request.meth |> Code.string_of_method in
                            ^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 67, characters 30-45:
 67 |     let referer = Header.get (Request.headers req) "referer" in
                                    ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 68, characters 27-42:
 68 |     let host = Header.get (Request.headers req) "host" in
                                 ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 69, characters 25-40:
 69 |     let ua = Header.get (Request.headers req) "user-agent" in
                               ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 70, characters 14-25:
 70 |     let uri = Request.uri req in
                    ^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 86, characters 31-41:
 86 |   let attrs_of_response (res : Response.t) =
                                     ^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Response
 Use Cohttp.Response directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 87, characters 15-30:
 87 |     let code = Response.status res in
                     ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Response
 Use Cohttp.Response directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 96, characters 18-33:
 96 |       Header.add (Request.headers req) header_x_ocaml_otel_traceparent
                        ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 109, characters 22-37:
 109 |     match Header.get (Request.headers req) name with
                             ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 120, characters 21-36:
 120 |       Header.remove (Request.headers req) header_x_ocaml_otel_traceparent
                            ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 139, characters 11-20:
 139 |       (f : Request.t -> 'a Lwt.t) =
                  ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 10, characters 14-23:
 10 |     ('conn -> Request.t -> 'body -> (Response.t * 'body) Lwt.t) ->
                    ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 10, characters 37-47:
 10 |     ('conn -> Request.t -> 'body -> (Response.t * 'body) Lwt.t) ->
                                           ^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Response
 Use Cohttp.Response directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 12, characters 4-13:
 12 |     Request.t ->
          ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 14, characters 5-15:
 14 |     (Response.t * 'body) Lwt.t
           ^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Response
 Use Cohttp.Response directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 39, characters 4-13:
 39 |     Request.t ->
          ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 40, characters 5-14:
 40 |     (Request.t -> 'a Lwt.t) ->
           ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 50, characters 39-48:
 50 |     ?from:[ `Internal | `External ] -> Request.t -> Otel.Scope.t option
                                             ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 55, characters 42-51:
 55 |   val set_trace_context : Otel.Scope.t -> Request.t -> Request.t
                                                ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 55, characters 55-64:
 55 |   val set_trace_context : Otel.Scope.t -> Request.t -> Request.t
                                                             ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 60, characters 29-38:
 60 |   val remove_trace_context : Request.t -> Request.t
                                   ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 60, characters 42-51:
 60 |   val remove_trace_context : Request.t -> Request.t
                                                ^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Request
 Use Cohttp.Request directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 189, characters 9-19:
 189 |         (Response.t * Cohttp_lwt.Body.t) Lwt.t =
                ^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Response
 Use Cohttp.Response directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 196, characters 25-40:
 196 |               let code = Response.status res in
                                ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Response
 Use Cohttp.Response directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 226, characters 25-40:
 226 |               let code = Response.status res in
                                ^^^^^^^^^^^^^^^
 Alert deprecated: module Cohttp_lwt.Response
 Use Cohttp.Response directly
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 233, characters 10-16:
 233 |   (module Traced : Cohttp_lwt.S.Client)
                 ^^^^^^
 Error: Signature mismatch:
        ...
        The value `set_cache' is required but not provided
        File "cohttp-lwt/src/s.ml", line 190, characters 2-30:
          Expected declaration
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>