lua-ml 0.9 is not compatible with ocaml 5
Uses Pervasives
```
\#=== ERROR while compiling lua-ml.0.9 =========================================#
\# context              2.2.0~alpha3~dev | linux/x86_64 | ocaml-base-compiler.5.1.0 | file:///home/opam/opam-repository
\# path                 ~/.opam/5.1/.opam-switch/build/lua-ml.0.9
\# command              ~/.opam/opam-init/hooks/sandbox.sh build make lib
\# exit-code            2
\# env-file             ~/.opam/log/lua-ml-7-224212.env
\# output-file          ~/.opam/log/lua-ml-7-224212.out
\### output ###
\# make -C src all
\# make[1]: Entering directory '/home/opam/.opam/5.1/.opam-switch/build/lua-ml.0.9/src'
\# ocamlyacc luaparsex.mly
\# # Some handwritten bits are required for the parser interface
\# rm luaparsex.mli
\# mv luaparsex.ml luaparser.ml
\# cp _luaparser.mli luaparser.mli
\# make[1]: Leaving directory '/home/opam/.opam/5.1/.opam-switch/build/lua-ml.0.9/src'
\# ocamlbuild -I src src/lua-std.cmxa src/lua-std.cma src/lua-std.cmxs
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/lua.ml > src/lua.ml.depends
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/lua.mli > src/lua.mli.depends
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/luaast.mli > src/luaast.mli.depends
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/luavalue.mli > src/luavalue.mli.depends
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/luasrcmap.mli > src/luasrcmap.mli.depends
\# /home/opam/.opam/5.1/bin/ocamlc.opt -c -I src -o src/luasrcmap.cmi src/luasrcmap.mli
\# /home/opam/.opam/5.1/bin/ocamlc.opt -c -I src -o src/luavalue.cmi src/luavalue.mli
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/luaparser.mli > src/luaparser.mli.depends
\# /home/opam/.opam/5.1/bin/ocamlc.opt -c -I src -o src/luaast.cmi src/luaast.mli
\# /home/opam/.opam/5.1/bin/ocamlc.opt -c -I src -o src/luaparser.cmi src/luaparser.mli
\# /home/opam/.opam/5.1/bin/ocamlc.opt -c -I src -o src/lua.cmi src/lua.mli
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/luaast.ml > src/luaast.ml.depends
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/luavalue.ml > src/luavalue.ml.depends
\# /home/opam/.opam/5.1/bin/ocamllex.opt -q src/luafloat.mll
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/luafloat.ml > src/luafloat.ml.depends
\# /home/opam/.opam/5.1/bin/ocamlc.opt -c -I src -o src/luafloat.cmo src/luafloat.ml
\# /home/opam/.opam/5.1/bin/ocamldep.opt -modules src/luasrcmap.ml > src/luasrcmap.ml.depends
\# /home/opam/.opam/5.1/bin/ocamlopt.opt -c -I src -o src/luafloat.cmx src/luafloat.ml
\# /home/opam/.opam/5.1/bin/ocamlopt.opt -c -I src -o src/luasrcmap.cmx src/luasrcmap.ml
\# + /home/opam/.opam/5.1/bin/ocamlopt.opt -c -I src -o src/luasrcmap.cmx src/luasrcmap.ml
\# File "src/luasrcmap.ml", line 100, characters 47-61:
\# 100 |         let (=$=) : string -> string -> bool = Pervasives.(=) in
\#                                                      ^^^^^^^^^^^^^^
\# Error: Unbound module Pervasives
\# Command exited with code 2.
\# Hint: Recursive traversal of subdirectories was not enabled for this build,
\#   as the working directory does not look like an ocamlbuild project (no
\#   '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
\#   you should add the option "-r" or create an empty '_tags' file.
\#
\#   To enable recursive traversal for some subdirectories only, you can use the
\#   following '_tags' file:
\#
\#       true: -traverse
\#       <dir1> or <dir2>: traverse
\#
\# make: *** [Makefile:8: lib] Error 10
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>