ppx_minidebug is not compatible with new ppx_sexp_conv
due to some issues with ppxlib 0.36.0
Seen on https://github.com/ocaml/opam-repository/pull/27958

```
=== ERROR while compiling ppx_minidebug.2.2.0 ================================#
 context              2.3.0 | linux/x86_64 | ocaml-base-compiler.5.3.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.3/.opam-switch/build/ppx_minidebug.2.2.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ppx_minidebug -j 255 @install
 exit-code            1
 env-file             ~/.opam/log/ppx_minidebug-7-521fc7.env
 output-file          ~/.opam/log/ppx_minidebug-7-521fc7.out
 (cd _build/default && /home/opam/.opam/5.3/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I .ppx_minidebug.objs/byte -I /home/opam/.opam/5.3/lib/ocaml-compiler-libs/common -I /home/opam/.opam/5.3/lib/ocaml-compiler-libs/shadow -I /home/opam/.opam/5.3/lib/ocaml/compiler-libs -I /home/opam/.opam/5.3/lib/ppx_derivers -I /home/opam/.opam/5.3/lib/ppxlib -I /home/opam/.opam/5.3/lib/ppxlib/ast -I /home/opam/.opam/5.3/lib/ppxlib/astlib -I /home/opam/.opam/5.3/lib/ppxlib/print_diff -I /home/opam/.opam/5.3/lib/ppxlib/stdppx -I /home/opam/.opam/5.3/lib/ppxlib/traverse_builtins -I /home/opam/.opam/5.3/lib/re -I /home/opam/.opam/5.3/lib/seq -I /home/opam/.opam/5.3/lib/sexplib0 -I /home/opam/.opam/5.3/lib/stdlib-shims -no-alias-deps -o .ppx_minidebug.objs/byte/ppx_minidebug.cmo -c -impl ppx_minidebug.pp.ml)
 File "ppx_minidebug.ml", line 67, characters 51-52:
 67 |   | Ptyp_alias (typ, x) -> typ2str typ ^ " as '" ^ x
                                                         ^
 Error: The value "x" has type "string Ppxlib.loc" = "string Location.loc"
        but an expression was expected of type "string"
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>