piaf 0.1.0 requires result
It vendors some libraries that require it:
```
=== ERROR while compiling piaf.0.1.0 =========================================#
 context              2.2.0~alpha3 | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/piaf.0.1.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p piaf -j 71
 exit-code            1
 env-file             ~/.opam/log/piaf-7-ccfb59.env
 output-file          ~/.opam/log/piaf-7-ccfb59.out
 File "vendor/dune", line 95, characters 3-9:
 95 |    result
         ^^^^^^
 Error: Library "result" not found.
 -> required by library "piaf.multipart_form" in
    _build/default/vendor/multipart_form/lib
 -> required by _build/default/META.piaf
 -> required by _build/install/default/lib/piaf/META
 -> required by _build/default/piaf.install
 -> required by alias install
 File "vendor/dune", line 60, characters 3-9:
 60 |    result
         ^^^^^^
 Error: Library "result" not found.
 -> required by library "piaf.h2" in _build/default/vendor/ocaml-h2/lib
 -> required by _build/default/META.piaf
 -> required by _build/install/default/lib/piaf/META
 -> required by _build/default/piaf.install
 -> required by alias install
 File "vendor/dune", line 8, characters 42-48:
 8 |   (libraries angstrom faraday bigstringaf result)))
                                               ^^^^^^
 Error: Library "result" not found.
 -> required by library "piaf.httpaf" in _build/default/vendor/httpaf/lib
 -> required by _build/default/META.piaf
 -> required by _build/install/default/lib/piaf/META
 -> required by _build/default/piaf.install
 -> required by alias install
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>