touist: add upper bound on minisat
With 0.6 fails with 
```
# File "src/sat.ml", line 86, characters 20-44:
# 86 |     | cur::next -> (Minisat.Raw.add_clause_a solver (Array.of_list cur)) && (add_clauses solver next)
#                          ^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Minisat.Raw
```
since the `Raw` module is no longer exposed