Older datalog versions FTBFS on newer OCaml
Something about how it is built is wrong, a mix of `-for-pack` and not
`-for-pack` causes it to fail:

> File "datalog_cli.ml", line 1:
> Error: "datalog/lexer.cmx" was built with "-for-pack Datalog", but the
>        current unit "Datalog_cli" is not
> Command exited with code 2.