capnp-rpc-net: add missing upper-bound on x509
Error was:

    File "capnp-rpc-net/auth.ml", line 139, characters 12-22:
    139 |     | Error (`Msg err) -> failwith (Printf.sprintf "x509 signing failed: %s" err)
                  ^^^^^^^^^^
    Error: This pattern matches values of type [? `Msg of 'a ]
           but a pattern was expected which matches values of type
             X509.Validation.signature_error
           The second variant type does not allow tag(s) `Msg