Increase lowerbound on dune for caisar-onnx.0.2
It fails when building with ocaml-protoc-plugin.4.2.0 with 2.9.3:

File "lib/onnx/dune", line 11, characters 11-30:
11 |   (package ocaml-protoc-plugin))
                ^^^^^^^^^^^^^^^^^^^
Error: Package ocaml-protoc-plugin does not exist

Note that all subsequent versions of ocaml-proto-plugin require at least
Dune 3.2, so the simple lowerbound is sufficient - there's no version of
dependencies where this package can succesfully build with Dune 2.9.x