dream-html not compatible with recent ppxlib
File "ppx/ppx.ml", line 30, characters 26-66:
30 |         (pstr_value drop (value_binding ~pat:__ ~expr:(estring __) ^:: nil)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 5 [ignored-partial-application]: this function application is partial,
maybe some arguments are missing.
File "ppx/ppx.ml", line 30, characters 26-66:
30 |         (pstr_value drop (value_binding ~pat:__ ~expr:(estring __) ^:: nil)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type
         constraint_:(Ppxlib__.Import.value_constraint option, 'a, 'b)
                     Ppxlib__.Ast_pattern0.t ->
         (Ppxlib__.Import.value_binding,
          Ppxlib__.Import.pattern -> string -> 'a, 'b)
         Ppxlib__.Ast_pattern0.t
       but an expression was expected of type
         ('c, 'd, 'e) Ppxlib.Ast_pattern.t =
           ('c, 'd, 'e) Ppxlib__Ast_pattern0.t
File "ppx/ppx.ml", line 30, characters 26-66:
30 |         (pstr_value drop (value_binding ~pat:__ ~expr:(estring __) ^:: nil)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 5 [ignored-partial-application]: this function application is partial,
maybe some arguments are missing.
File "ppx/ppx.ml", line 30, characters 26-66:
30 |         (pstr_value drop (value_binding ~pat:__ ~expr:(estring __) ^:: nil)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type
         constraint_:(Ppxlib__.Import.value_constraint option, 'a, 'b)
                     Ppxlib__.Ast_pattern0.t ->
         (Ppxlib__.Import.value_binding,
          Ppxlib__.Import.pattern -> string -> 'a, 'b)
         Ppxlib__.Ast_pattern0.t
       but an expression was expected of type
         ('c, 'd, 'e) Ppxlib.Ast_pattern.t =
           ('c, 'd, 'e) Ppxlib__Ast_pattern0.t