sundialsml: add x-ci-accept-faulures because of deprecation errors.
Like this one:

> lsolvers/sundials_nonlinearsolver_ml.c:980:5: error: 'SUNNonlinSolSetInfoFile_Newton' is deprecated: Use SUNLogger_SetInfoFilename instead [-Werror=deprecated-declarations]

Signed-off-by: Kakadu <kakadu.hafanana@gmail.com>