paf, paf-cohttp needs upper bounds on cohttp 6
Failures:
```
=== ERROR while compiling paf.0.0.3 ==========================================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/paf.0.0.3
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p paf -j 71
 exit-code            1
 env-file             ~/.opam/log/paf-8-cbb7f2.env
 output-file          ~/.opam/log/paf-8-cbb7f2.out
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.paf.objs/byte -I /home/opam/.opam/4.14/lib/bigarray-compat -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/rresult -intf-suffix .ml -no-alias-deps -o lib/.paf.objs/byte/paf.cmo -c -impl lib/paf.ml)
 File "lib/paf.ml", line 116, characters 24-35:
 116 |               let len = Cstruct.len v in
                               ^^^^^^^^^^^
 Alert deprecated: Cstruct.len
 len is deprecated, you should use length instead.
 File "lib/paf.ml", line 119, characters 55-66:
 119 |                 Ke.Rke.N.push flow.queue ~blit ~length:Cstruct.len ~off:0 ~len v
                                                              ^^^^^^^^^^^
 Alert deprecated: Cstruct.len
 len is deprecated, you should use length instead.
 File "lib/paf.ml", line 262, characters 18-29:
 262 |         let len = Cstruct.len v in
                         ^^^^^^^^^^^
 Alert deprecated: Cstruct.len
 len is deprecated, you should use length instead.
 File "lib/paf.ml", line 264, characters 47-58:
 264 |         Ke.Rke.N.push flow.queue ~blit ~length:Cstruct.len ~off:0 ~len v ;
                                                      ^^^^^^^^^^^
 Alert deprecated: Cstruct.len
 len is deprecated, you should use length instead.
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.paf_cohttp.objs/byte -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigarray-compat -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cohttp -I /home/opam/.opam/4.14/lib/cohttp-lwt -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/http -I /home/opam/.opam/4.14/lib/httpaf -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/re -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/rresult -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uri-sexp -I lib/.paf.objs/byte -intf-suffix .ml -no-alias-deps -o lib/.paf_cohttp.objs/byte/paf_cohttp.cmo -c -impl lib/paf_cohttp.ml)
 File "lib/paf_cohttp.ml", line 1:
 Error: The implementation lib/paf_cohttp.ml
        does not match the interface lib/.paf_cohttp.objs/byte/paf_cohttp.cmi:
         The value `set_cache' is required but not provided
        File "cohttp-lwt/src/s.ml", line 190, characters 2-30:
          Expected declaration
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -g -I lib/.paf.objs/byte -I lib/.paf.objs/native -I /home/opam/.opam/4.14/lib/bigarray-compat -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/rresult -intf-suffix .ml -no-alias-deps -o lib/.paf.objs/native/paf.cmx -c -impl lib/paf.ml)
 File "lib/paf.ml", line 116, characters 24-35:
 116 |               let len = Cstruct.len v in
                               ^^^^^^^^^^^
 Alert deprecated: Cstruct.len
 len is deprecated, you should use length instead.
 File "lib/paf.ml", line 119, characters 55-66:
 119 |                 Ke.Rke.N.push flow.queue ~blit ~length:Cstruct.len ~off:0 ~len v
                                                              ^^^^^^^^^^^
 Alert deprecated: Cstruct.len
 len is deprecated, you should use length instead.
 File "lib/paf.ml", line 262, characters 18-29:
 262 |         let len = Cstruct.len v in
                         ^^^^^^^^^^^
 Alert deprecated: Cstruct.len
 len is deprecated, you should use length instead.
 File "lib/paf.ml", line 264, characters 47-58:
 264 |         Ke.Rke.N.push flow.queue ~blit ~length:Cstruct.len ~off:0 ~len v ;
                                                      ^^^^^^^^^^^
 Alert deprecated: Cstruct.len
 len is deprecated, you should use length instead.
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.paf_mirage.objs/byte -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/asn1-combinators -I /home/opam/.opam/4.14/lib/base/caml -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigarray-compat -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/cstruct-sexp -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/duration -I /home/opam/.opam/4.14/lib/eqaf -I /home/opam/.opam/4.14/lib/eqaf/bigstring -I /home/opam/.opam/4.14/lib/eqaf/cstruct -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/gmap -I /home/opam/.opam/4.14/lib/h2 -I /home/opam/.opam/4.14/lib/hkdf -I /home/opam/.opam/4.14/lib/hpack -I /home/opam/.opam/4.14/lib/httpaf -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-clock -I /home/opam/.opam/4.14/lib/mirage-crypto -I /home/opam/.opam/4.14/lib/mirage-crypto-ec -I /home/opam/.opam/4.14/lib/mirage-crypto-pk -I /home/opam/.opam/4.14/lib/mirage-crypto-rng -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/mirage-kv -I /home/opam/.opam/4.14/lib/mirage-protocols -I /home/opam/.opam/4.14/lib/mirage-stack -I /home/opam/.opam/4.14/lib/mirage-time -I /home/opam/.opam/4.14/lib/optint -I /home/opam/.opam/4.14/lib/parsexp -I /home/opam/.opam/4.14/lib/pbkdf -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/psq -I /home/opam/.opam/4.14/lib/ptime -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/rresult -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stdlib-shims -I /home/opam/.opam/4.14/lib/tls -I /home/opam/.opam/4.14/lib/tls-mirage -I /home/opam/.opam/4.14/lib/x509 -I /home/opam/.opam/4.14/lib/zarith -I lib/.alpn.objs/byte -I lib/.paf.objs/byte -intf-suffix .ml -no-alias-deps -o lib/.paf_mirage.objs/byte/paf_mirage.cmo -c -impl lib/paf_mirage.ml)
 File "lib/paf_mirage.ml", line 161, characters 4-20:
 161 |     Stack.listen_tcp ~port stack listener ;
           ^^^^^^^^^^^^^^^^
 Alert deprecated: Stack.listen_tcp
 use TCP.listen instead (since mirage-protocols 6.0.0).
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -g -I lib/.paf_cohttp.objs/byte -I lib/.paf_cohttp.objs/native -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigarray-compat -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cohttp -I /home/opam/.opam/4.14/lib/cohttp-lwt -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/http -I /home/opam/.opam/4.14/lib/http/__private__/http_bytebuffer -I /home/opam/.opam/4.14/lib/httpaf -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/re -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/rresult -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uri-sexp -I lib/.paf.objs/byte -I lib/.paf.objs/native -intf-suffix .ml -no-alias-deps -o lib/.paf_cohttp.objs/native/paf_cohttp.cmx -c -impl lib/paf_cohttp.ml)
 File "lib/paf_cohttp.ml", line 1:
 Error: The implementation lib/paf_cohttp.ml
        does not match the interface lib/.paf_cohttp.objs/byte/paf_cohttp.cmi:
         The value `set_cache' is required but not provided
        File "cohttp-lwt/src/s.ml", line 190, characters 2-30:
          Expected declaration
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -g -I lib/.paf_mirage.objs/byte -I lib/.paf_mirage.objs/native -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/asn1-combinators -I /home/opam/.opam/4.14/lib/base/caml -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigarray-compat -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/cstruct-sexp -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/duration -I /home/opam/.opam/4.14/lib/eqaf -I /home/opam/.opam/4.14/lib/eqaf/bigstring -I /home/opam/.opam/4.14/lib/eqaf/cstruct -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/gmap -I /home/opam/.opam/4.14/lib/h2 -I /home/opam/.opam/4.14/lib/hkdf -I /home/opam/.opam/4.14/lib/hpack -I /home/opam/.opam/4.14/lib/httpaf -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-clock -I /home/opam/.opam/4.14/lib/mirage-crypto -I /home/opam/.opam/4.14/lib/mirage-crypto-ec -I /home/opam/.opam/4.14/lib/mirage-crypto-pk -I /home/opam/.opam/4.14/lib/mirage-crypto-rng -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/mirage-kv -I /home/opam/.opam/4.14/lib/mirage-protocols -I /home/opam/.opam/4.14/lib/mirage-stack -I /home/opam/.opam/4.14/lib/mirage-time -I /home/opam/.opam/4.14/lib/optint -I /home/opam/.opam/4.14/lib/parsexp -I /home/opam/.opam/4.14/lib/pbkdf -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/psq -I /home/opam/.opam/4.14/lib/ptime -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/rresult -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stdlib-shims -I /home/opam/.opam/4.14/lib/tls -I /home/opam/.opam/4.14/lib/tls-mirage -I /home/opam/.opam/4.14/lib/x509 -I /home/opam/.opam/4.14/lib/zarith -I lib/.alpn.objs/byte -I lib/.alpn.objs/native -I lib/.paf.objs/byte -I lib/.paf.objs/native -intf-suffix .ml -no-alias-deps -o lib/.paf_mirage.objs/native/paf_mirage.cmx -c -impl lib/paf_mirage.ml)
 File "lib/paf_mirage.ml", line 161, characters 4-20:
 161 |     Stack.listen_tcp ~port stack listener ;
           ^^^^^^^^^^^^^^^^
 Alert deprecated: Stack.listen_tcp
 use TCP.listen instead (since mirage-protocols 6.0.0).
```

```
=== ERROR while compiling paf-cohttp.0.5.0 ===================================#
 context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/paf-cohttp.0.5.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p paf-cohttp -j 255
 exit-code            1
 env-file             ~/.opam/log/paf-cohttp-7-c8cdae.env
 output-file          ~/.opam/log/paf-cohttp-7-c8cdae.out
\### output ###
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlopt.opt -w -40 -g -I lib/.paf_cohttp.objs/byte -I lib/.paf_cohttp.objs/native -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cohttp -I /home/opam/.opam/4.14/lib/cohttp-lwt -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/http -I /home/opam/.opam/4.14/lib/http/__private__/http_bytebuffer -I /home/opam/.opam/4.14/lib/httpaf -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/paf -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/re -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uri-sexp -intf-suffix .ml -no-alias-deps -o lib/.paf_cohttp.objs/native/paf_cohttp.cmx -c -impl lib/paf_cohttp.ml)
 File "lib/paf_cohttp.ml", line 1:
 Error: The implementation lib/paf_cohttp.ml
        does not match the interface lib/.paf_cohttp.objs/byte/paf_cohttp.cmi:
         The value `set_cache' is required but not provided
        File "cohttp-lwt/src/s.ml", line 190, characters 2-30:
          Expected declaration
 (cd _build/default && /home/opam/.opam/4.14/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.paf_cohttp.objs/byte -I /home/opam/.opam/4.14/lib/angstrom -I /home/opam/.opam/4.14/lib/base64 -I /home/opam/.opam/4.14/lib/bigstringaf -I /home/opam/.opam/4.14/lib/cohttp -I /home/opam/.opam/4.14/lib/cohttp-lwt -I /home/opam/.opam/4.14/lib/cstruct -I /home/opam/.opam/4.14/lib/domain-name -I /home/opam/.opam/4.14/lib/faraday -I /home/opam/.opam/4.14/lib/fmt -I /home/opam/.opam/4.14/lib/http -I /home/opam/.opam/4.14/lib/httpaf -I /home/opam/.opam/4.14/lib/ipaddr -I /home/opam/.opam/4.14/lib/ke -I /home/opam/.opam/4.14/lib/logs -I /home/opam/.opam/4.14/lib/lwt -I /home/opam/.opam/4.14/lib/macaddr -I /home/opam/.opam/4.14/lib/mimic -I /home/opam/.opam/4.14/lib/mirage-flow -I /home/opam/.opam/4.14/lib/paf -I /home/opam/.opam/4.14/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.14/lib/re -I /home/opam/.opam/4.14/lib/result -I /home/opam/.opam/4.14/lib/seq -I /home/opam/.opam/4.14/lib/sexplib0 -I /home/opam/.opam/4.14/lib/stringext -I /home/opam/.opam/4.14/lib/uri -I /home/opam/.opam/4.14/lib/uri-sexp -intf-suffix .ml -no-alias-deps -o lib/.paf_cohttp.objs/byte/paf_cohttp.cmo -c -impl lib/paf_cohttp.ml)
 File "lib/paf_cohttp.ml", line 1:
 Error: The implementation lib/paf_cohttp.ml
        does not match the interface lib/.paf_cohttp.objs/byte/paf_cohttp.cmi:
         The value `set_cache' is required but not provided
        File "cohttp-lwt/src/s.ml", line 190, characters 2-30:
          Expected declaration
```
Signed-off-by: Marcello Seri <marcello.seri@gmail.com>