Require Lwt 2.4.7 for `Lwt.Infix`
The error message when using an older version is:

```
File "src/tube.ml", line 12, characters 7-16:
Error: Unbound module Lwt.Infix
```