atdgen 2.{0-2}: requires upper bound on atd < 2.3
Fixes

\#=== ERROR while compiling atdgen.2.2.1 =======================================#
\# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.13.1 | file:///home/opam/opam-repository
\# path                 ~/.opam/4.13/.opam-switch/build/atdgen.2.2.1
\# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p atdgen -j 31 @install
\# exit-code            1
\# env-file             ~/.opam/log/atdgen-2601-a2703f.env
\# output-file          ~/.opam/log/atdgen-2601-a2703f.out
\### output ###
\# (cd _build/default && /home/opam/.opam/4.13/bin/ocamlopt.opt -w -40 -w -27 -safe-string -g -I atdgen/src/.atdgen_emit.objs/byte -I atdgen/src/.atdgen_emit.objs/native -I /home/opam/.opam/4.13/lib/atd -I /home/opam/.opam/4.13/lib/biniou -I /home/opam/.opam/4.13/lib/easy-format -I /home/opam/.opam/4.13/lib/yojson -intf-suffix .ml -no-alias-deps -open Atdgen_emit -o atdgen/src/.atdgen_emit.objs/native/atdgen_emit__Ocaml.cmx -c -impl atdgen/src/ocaml.ml)
\# File "atdgen/src/ocaml.ml", line 618, characters 12-24:
\# 618 | let split = Re.Str.split (Re.Str.regexp " ")
\#                   ^^^^^^^^^^^^
\# Error: Unbound module Re

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>