dune-secondary 3.16 needs OCaml < 5.4
The error message is below. It complains about field 'out_width' that is
available in Format module since OCaml 5.4

> File "vendor/notty/src/notty.ml", lines 387-397, characters 43-7:
  Error: Some record fields are undefined: out_width

Signed-off-by: Kakadu <kakadu.hafanana@gmail.com>