memtrace: doesn't work with OCaml 5
```
 context     2.1.2 | macos/arm64 | ocaml.5.0.0 | https://opam.ocaml.org#21aa7ced
 path        ~/git/irmin/_opam/.opam-switch/build/memtrace.0.2.2
 command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p memtrace -j 9 @install
 exit-code   1
 env-file    ~/.opam/log/memtrace-6831-fed1d4.env
 output-file ~/.opam/log/memtrace-6831-fed1d4.out
 ## output ###
 [...]
 353 |     h lxor (h lsr 23)
 354 |   let equal (a : t) (b : t) = a = b
 355 | end)
 Error: Modules do not match:
        sig
          type t = int
          val hash : 'a -> t -> int
          val equal : t -> t -> bool
        end
      is not included in Hashtbl.SeededHashedType
      The value `seeded_hash' is required but not provided
      File "hashtbl.mli", line 399, characters 4-36: Expected declaration
```