ocaml 5: restrict qtest releases
They rely on `String.capitalize`:

    #=== ERROR while compiling qtest.2.10.1 =======================================#
    # context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
    # path                 ~/.opam/5.0/.opam-switch/build/qtest.2.10.1
    # command              ~/.opam/opam-init/hooks/sandbox.sh build dune build @install -j 255 -p qtest
    # exit-code            1
    # env-file             ~/.opam/log/qtest-8-63a33a.env
    # output-file          ~/.opam/log/qtest-8-63a33a.out
    ### output ###
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -w +a-4-29-44-50@8 -warn-error -a -safe-string -g -bin-annot -I src/.qtest_bin.eobjs/byte -I /home/opam/.opam/5.0/lib/bytes -no-alias-deps -o src/.qtest_bin.eobjs/byte/misclex.cmo -c -impl src/misclex.ml)
    # File "src/misclex.ml", line 1:
    # Warning 70 [missing-mli]: Cannot find interface file.
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -w +a-4-29-44-50@8 -warn-error -a -safe-string -g -bin-annot -I src/.qtest_bin.eobjs/byte -I /home/opam/.opam/5.0/lib/bytes -no-alias-deps -o src/.qtest_bin.eobjs/byte/core.cmo -c -impl src/core.ml)
    # File "src/core.ml", line 1:
    # Warning 70 [missing-mli]: Cannot find interface file.
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -w +a-4-29-44-50@8 -warn-error -a -safe-string -g -bin-annot -I src/.qtest_bin.eobjs/byte -I /home/opam/.opam/5.0/lib/bytes -no-alias-deps -o src/.qtest_bin.eobjs/byte/qtest_bin.cmo -c -impl src/qtest_bin.ml)
    # File "src/qtest_bin.mll", line 225, characters 4-21:
    # Error: Unbound value String.capitalize