some session-* packages require the result library
They explicitly link against it.
Failures are all similar and look like the following
```
=== ERROR while compiling session-cookie-lwt.0.1.8 ===========================#
 context              2.2.0~alpha4~dev | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/session-cookie-lwt.0.1.8
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p session-cookie-lwt -j 255 @install
 exit-code            1
 env-file             ~/.opam/log/session-cookie-lwt-7-f8b6e2.env
 output-file          ~/.opam/log/session-cookie-lwt-7-f8b6e2.out
 File "session-cookie-lwt/dune", line 4, characters 16-22:
 4 |  (libraries lwt result session-cookie))
                     ^^^^^^
 Error: Library "result" not found.
 -> required by library "session-cookie-lwt" in
    _build/default/session-cookie-lwt
 -> required by _build/default/META.session-cookie-lwt
 -> required by _build/install/default/lib/session-cookie-lwt/META
 -> required by _build/default/session-cookie-lwt.install
 -> required by alias install
```

Fixes https://github.com/ocaml/opam-repository/issues/24944

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>