bechamel-js links against result
Fails with
```
=== ERROR while compiling bechamel-js.0.4.0 ==================================#
 context              2.2.0~alpha4~dev | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/bechamel-js.0.4.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p bechamel-js -j 255
 exit-code            1
 env-file             ~/.opam/log/bechamel-js-7-ed3984.env
 output-file          ~/.opam/log/bechamel-js-7-ed3984.out
 File "lib/js/dune", line 4, characters 33-39:
 4 |  (libraries bechamel fmt rresult result json-data-encoding jsonm))
                                      ^^^^^^
 Error: Library "result" not found.
 -> required by library "bechamel-js" in _build/default/lib/js
 -> required by _build/default/META.bechamel-js
 -> required by _build/install/default/lib/bechamel-js/META
 -> required by _build/default/bechamel-js.install
 -> required by alias install
```
Signed-off-by: Marcello Seri <marcello.seri@gmail.com>