randoml.0.1.5 needs OCaml < 5
cargo:warning=vendor/boxroot/boxroot.c:23:10: fatal error: caml/compact.h: No such file or directory

This file was removed in OCaml 5 when multicore runtime was introduced

Signed-off-by: Kakadu <kakadu.hafanana@gmail.com>