ocaml 5: restrict msat releases
They rely on `Pervasives`:

    #=== ERROR while compiling msat.0.8 ===========================================#
    # context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
    # path                 ~/.opam/5.0/.opam-switch/build/msat.0.8
    # command              ~/.opam/opam-init/hooks/sandbox.sh build dune build @install -p msat -j 127
    # exit-code            1
    # env-file             ~/.opam/log/msat-8-63a4cf.env
    # output-file          ~/.opam/log/msat-8-63a4cf.out
    ### output ###
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -warn-error -3 -w +a-4-42-44-48-50-58-32-60@8 -color always -safe-string -g -bin-annot -I src/core/.msat.objs/byte -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/iter -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -no-alias-deps -open Msat__ -o src/core/.msat.objs/byte/msat__Heap_intf.cmo -c -impl src/core/Heap_intf.ml)
    # File "src/core/Heap_intf.ml", line 1:
    # Warning 70 [missing-mli]: Cannot find interface file.
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -warn-error -3 -w +a-4-42-44-48-50-58-32-60@8 -color always -safe-string -g -bin-annot -I src/core/.msat.objs/byte -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/iter -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -no-alias-deps -open Msat__ -o src/core/.msat.objs/byte/msat__Solver_intf.cmo -c -impl src/core/Solver_intf.ml)
    # File "src/core/Solver_intf.ml", line 1:
    # Warning 70 [missing-mli]: Cannot find interface file.
    # (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -warn-error -3 -w +a-4-42-44-48-50-58-32-60@8 -color always -safe-string -g -bin-annot -I src/core/.msat.objs/byte -I /home/opam/.opam/5.0/lib/bytes -I /home/opam/.opam/5.0/lib/iter -I /home/opam/.opam/5.0/lib/result -I /home/opam/.opam/5.0/lib/seq -no-alias-deps -open Msat__ -o src/core/.msat.objs/byte/msat__Internal.cmo -c -impl src/core/Internal.ml)
    # File "src/core/Internal.ml", line 235, characters 31-49:
    # 235 |     let[@inline] compare a b = Pervasives.compare a.aid b.aid
    #                                      ^^^^^^^^^^^^^^^^^^
    # Error: Unbound module Pervasives