randoml.0.1.5 needs OCaml < 5
cargo:warning=vendor/boxroot/boxroot.c:23:10: fatal error: caml/compact.h: No such file or directory

This file was removed in OCaml 5.2 when multicore runtime reimplemented
compaction: https://github.com/ocaml/ocaml/pull/12193, and
https://github.com/ocaml/ocaml/blob/5.2.1/Changes#L71

Signed-off-by: Kakadu <kakadu.hafanana@gmail.com>