leveldb.1.0.2 seems unbuildable
```
$ ocamlfind ocamlopt -package unix,threads,oUnit -w +a-4-6-9-27-28-30..99 -warn-error +a-4-6-9-18-27-28-30..99 -annot -thread -inline 100 -I . -I ../src -o test.opt ../src/leveldb.cmxa test_00util.cmx test.cmx -linkpkg
/usr/bin/ld: ../src/libcamlleveldb.a(leveldb_stubs.o): undefined reference to symbol '_ZdlPvm@@CXXABI_1.3.9'
//usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
```

This error is similar to the snappy 0.0.1 error reported in
  de99d2a00c9c723f352b3f7c73a1de8f78f676ca.