Add constraints for efl
1) it uses function called 'effect' so clashes with a new keyword.
   That's why ocaml < 5.3 is required

2) ./configure fails on new systems with an error about missing
   autoconf-1.16. The './autogen.sh' should be called to regenerate
   './confugure'

3) In some distros gcc is too new:

   error: implicit declaration of function 'copy_string'; did you mean 'copy_string_opt'? [-Wimplicit-function-declaration]

Signed-off-by: Kakadu <kakadu.hafanana@gmail.com>