dkml-install-installer: depends on re
```
=== ERROR while compiling dkml-install-installer.0.5.2 =======================#
 context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.5.2.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.2/.opam-switch/build/dkml-install-installer.0.5.2
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dkml-install-installer -j 31 --promote-install-files=false @install
 exit-code            1
 env-file             ~/.opam/log/dkml-install-installer-8-ff0f83.env
 output-file          ~/.opam/log/dkml-install-installer-8-ff0f83.out
 File "installer/ml-generator/lib/dune", line 3, characters 37-39:
 3 |  (libraries dkml-install.api bos fmt re))
                                          ^^
 Error: Library "re" not found.
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>