Add an OCaml 5.4.0 upper bound on bogue.20250224
It is failing with
```
=== ERROR while compiling bogue.20250224 =====================================#
 context              2.5.0~beta1 | linux/x86_64 | ocaml-base-compiler.5.4.0 | file:///home/opam/opam-repository
 path                 ~/.opam/5.4/.opam-switch/build/bogue.20250224
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p bogue -j 255 @install
 exit-code            1
 env-file             ~/.opam/log/bogue-7-3e318b.env
 output-file          ~/.opam/log/bogue-7-3e318b.out
%## output ###
 (cd _build/default && /home/opam/.opam/5.4/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I lib/.bogue.objs/byte -I /home/opam/.opam/5.4/lib/ctypes -I /home/opam/.opam/5.4/lib/ctypes-foreign -I /home/opam/.opam/5.4/lib/integers -I /home/opam/.opam/5.4/lib/ocaml/str -I /home/opam/.opam/5.4/lib/ocaml/threads -I /home/opam/.opam/5.4/lib/ocaml/unix -I /home/opam/.opam/5.4/lib/stdlib-shims -I /home/opam/.opam/5.4/lib/tsdl -I /home/opam/.opam/5.4/lib/tsdl-image -I /home/opam/.opam/5.4/lib/tsdl-ttf -I /home/opam/.opam/5.4/lib/xdg -no-alias-deps -open Bogue__ -o lib/.bogue.objs/byte/bogue__B_file.cmo -c -impl lib/b_file.ml)
 File "lib/b_file.ml", line 1312, characters 37-38:
 1312 |     if compare x (unsafe_get a i1) = 0 then Some i1
                                             ^
 Error: The constant 0 has type int but an expression was expected of type
          'a array -> int
```

Due to 5.4.0 adding `Array.compare`.

Spotted on https://github.com/ocaml/opam-repository/pull/28962