jsoo: older jsoo need older lwt due to Lwt.async interface change
otherwise with lwt 5 you get:

```
Error: The implementation lib/lwt/lwt_js_events.pp.ml
        does not match the interface lib/lwt/.js_of_ocaml_lwt.objs/byte/js_of_ocaml_lwt__Lwt_js_events.cmi:
        Values do not match:
          val async : (unit -> unit Lwt.t) -> unit
        is not included in
          val async : (unit -> 'a Lwt.t) -> unit
        File "lib/lwt/lwt_js_events.mli", line 140, characters 0-38:
          Expected declaration
        File "lib/lwt/lwt_js_events.ml", line 25, characters 4-9:
          Actual declaration
```