uritemplate 0.1.0 is not compatible with atdgen 2.16
fails with
```
=== ERROR while compiling uritemplate.0.1.0 ==================================#
 context              2.4.0~alpha1~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/uritemplate.0.1.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune runtest -p uritemplate -j 255
 exit-code            1
 env-file             ~/.opam/log/uritemplate-7-995b8f.env
 output-file          ~/.opam/log/uritemplate-7-995b8f.out
 File "test/dune", line 3, characters 31-37:
 3 |   (libraries uritemplate oUnit atdgen))
                                    ^^^^^^
 Error: Library "atdgen" not found.
 -> required by _build/default/test/uritemplate_test.exe
 -> required by alias test/runtest in test/dune:2
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>