Mark comby as unavailable on arm64
The issue here is that core.uuid does not seem to exist on arm64, thus
depending on the library fails on arm64.

Error message:

File "lib/language/dune", line 6, characters 66-75:
6 |   (libraries comby.parsers comby.match comby.rewriter ppxlib core core.uuid))
                                                                      ^^^^^^^^^
Error: Library "core.uuid" not found.

Example of failing build:
https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/5326885410cbc592028e11fa6c22a60d04e09680/variant/extras,arm64-ocaml-5.1,comby.1.2.2