opentelemetry-cohttp-lwt 0.6 is not compatible with cohttp 6
Fails with
```
 File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 232, characters 10-16:
 232 |   (module Traced : Cohttp_lwt.S.Client)
                 ^^^^^^
 Error: Signature mismatch:
        ...
        The type `io' is required but not provided
        File "cohttp-lwt/src/s.ml", line 200, characters 11-32:
          Expected declaration
        The type `with_context' is required but not provided
        File "cohttp-lwt/src/s.ml", line 202, characters 11-48:
          Expected declaration
        The type `body' is required but not provided
        File "cohttp-lwt/src/s.ml", line 201, characters 11-29:
          Expected declaration
        The value `map_context' is required but not provided
        File "cohttp/src/client.ml", line 8, characters 2-68:
          Expected declaration
        The value `set_cache' is required but not provided
        File "cohttp-lwt/src/s.ml", line 204, characters 2-30:
          Expected declaration
```

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>