Do not build ocamlfind-lint on OCaml 5
FTBFS due to `Pervasives`:

    #=== ERROR while compiling ocamlfind-lint.0.1.0 ===============================#
    # context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
    # path                 ~/.opam/5.0/.opam-switch/build/ocamlfind-lint.0.1.0
    # command              ~/.opam/opam-init/hooks/sandbox.sh build make all
    # exit-code            2
    # env-file             ~/.opam/log/ocamlfind-lint-8-acaf0e.env
    # output-file          ~/.opam/log/ocamlfind-lint-8-acaf0e.out
    ### output ###
    # ocamlfind ocamlopt -o ocamlfind-lint -package findlib -linkpkg findlib_lint.ml
    # File "findlib_lint.ml", line 111, characters 36-54:
    # 111 |         let pkg_missing = List.sort Pervasives.compare pkg_missing in
    #                                           ^^^^^^^^^^^^^^^^^^
    # Error: Unbound module Pervasives