csv-lwt.2.{2,3} require at least 2.2 and are incompatible with 2.4
When installing lower versions:
```
#=== ERROR while compiling csv-lwt.2.2 ========================================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(https://github.com/Chris00/ocaml-csv/releases/download/2.2/csv-2.2.tbz)
# path                 ~/.opam/4.06/.opam-switch/build/csv-lwt.2.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p csv-lwt -j 31
# exit-code            1
# env-file             ~/.opam/log/csv-lwt-3967-8d5204.env
# output-file          ~/.opam/log/csv-lwt-3967-8d5204.out
### output ###
#       ocamlc lwt/.csv_lwt.objs/csv_lwt.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I lwt/.csv_lwt.objs -I /home/opam/.opam/4.06/lib/bytes -I /home/opam/.opam/4.06/lib/csv -I /home/opam/.opam/4.06/lib/lwt -I /home/opam/.opam/4.06/lib/result -no-alias-deps -open Csv_lwt__ -o lwt/.csv_lwt.objs/csv_lwt.cmo -c -impl lwt/csv_lwt.ml)
# File "src/csv.pp.ml", line 46, characters 5-19:
# Error: Unbound module Csv__Csv_utils
#     ocamlopt lwt/.csv_lwt.objs/csv_lwt.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -safe-string -g -I lwt/.csv_lwt.objs -I /home/opam/.opam/4.06/lib/bytes -I /home/opam/.opam/4.06/lib/csv -I /home/opam/.opam/4.06/lib/lwt -I /home/opam/.opam/4.06/lib/result -no-alias-deps -open Csv_lwt__ -o lwt/.csv_lwt.objs/csv_lwt.cmx -c -impl lwt/csv_lwt.ml)
# File "src/csv.pp.ml", line 46, characters 5-19:
# Error: Unbound module Csv__Csv_utils
```
and when installing 2.4:
```
#=== ERROR while compiling csv-lwt.2.2 ========================================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.05.0 | pinned(https://github.com/Chris00/ocaml-csv/releases/download/2.2/csv-2.2.tbz)
# path                 ~/.opam/4.05/.opam-switch/build/csv-lwt.2.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p csv-lwt -j 31
# exit-code            1
# env-file             ~/.opam/log/csv-lwt-3920-2f6979.env
# output-file          ~/.opam/log/csv-lwt-3920-2f6979.out
### output ###
#       ocamlc lwt/.csv_lwt.objs/csv_lwt.{cmi,cmti} (exit 2)
# (cd _build/default && /home/opam/.opam/4.05/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I lwt/.csv_lwt.objs -I /home/opam/.opam/4.05/lib/bytes -I /home/opam/.opam/4.05/lib/csv -I /home/opam/.opam/4.05/lib/lwt -I /home/opam/.opam/4.05/lib/result -no-alias-deps -open Csv_lwt__ -o lwt/.csv_lwt.objs/csv_lwt.cmi -c -intf lwt/csv_lwt.mli)
# File "lwt/csv_lwt.mli", line 102, characters 28-35:
# Error: Unbound module Csv.Row
```

The newer and older 2.* packages use `= version`