atdgen > 2.1 needs a lower bound on atdgen-runtime >= 2.1.0
This is because the generated code uses Atdgen_runtime.Oj_run.missing_field and all packages compiled with atd/atdgen >=1 and atdgen-runtime 2.0.0 are failing with
Error: Unbound value Atdgen_runtime.Oj_run.missing_field

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>