mirage-crypto does not work with newer eqaf (requires the .cstruct package):
```
=== ERROR while compiling mirage-crypto.0.11.0 ===============================#
 context              2.2.0~beta3~dev | linux/x86_64 | ocaml-base-compiler.4.14.2 | file:///home/opam/opam-repository
 path                 ~/.opam/4.14/.opam-switch/build/mirage-crypto.0.11.0
 command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p mirage-crypto -j 255
 exit-code            1
 env-file             ~/.opam/log/mirage-crypto-7-db30d0.env
 output-file          ~/.opam/log/mirage-crypto-7-db30d0.out
 ## output ###
 File "src/dune", line 4, characters 20-32:
 4 |  (libraries cstruct eqaf.cstruct)
                         ^^^^^^^^^^^^
 Error: Library "eqaf.cstruct" not found.
 -> required by library "mirage-crypto" in _build/default/src
 -> required by _build/default/META.mirage-crypto
 -> required by _build/install/default/lib/mirage-crypto/META
 -> required by _build/default/mirage-crypto.install
 -> required by alias install
```